### ISSUE TITLE
Link to creativecommons.org in the main navigation

### ISSUE THREAD

**Issue by kgodey** [creativecommons/creativecommons.github.io-source#103]
Currently there's no easy way to get from CC Open Source to creativecommons.org, we should add a link to it in the main navigation.

**Comment by enobeeeeeee** [comment]
Hi, am an outreachy applicant, would love to work on this.

**Comment by kgodey** [comment]
Go ahead

**Comment by krysal** [comment]
Hello, I made a proposal to add the link since there is not much activitie here for last 7 days.
Please @kgodey check if it's okay this way.
