### ISSUE TITLE
Generate new author and category pages automatically.

### ISSUE THREAD

**Issue by kgodey** [creativecommons/creativecommons.github.io-source#107]
**Is your feature request related to a problem? Please describe.**
Category and author pages have to be added manually for new authors and categories despite having enough information to generate basic pages automatically. This makes the process of adding a new blog post take longer. See the instructions on https://opensource.creativecommons.org/community/write-a-blog-post/, we could reduce a couple of steps.

**Describe the solution you'd like**
Whenever Lektor builds its static files, it should create missing author or category files for new blog posts.

**Describe alternatives you've considered**
Keep doing it manually like we do now, but that's a pain.

**Comment by SamOdum** [comment]
Hello @kgodey , I am an Outreachy applicant. Please may I work on this issue?

**Comment by kgodey** [comment]
Sure @SamOdum, I see you've commented on a couple of other issues on this repo as well, please pick one issue at a time so that others have a chance too. Let me know which one you want to tackle first and I'll mark that one as in progress.

**Comment by chimenekouomogne** [comment]
Hi @kgodey ! I'am an outreachy applicant , i have just received your mail according to the other project that is already in progress. Please is it possible for me to work on this one ?

**Comment by kgodey** [comment]
Yes, go ahead

**Comment by chimenekouomogne** [comment]
Thank you @Kriti 

Envoyé depuis Yahoo Mail pour Android 
 
  Le lun., oct. 21, 2019 à 18:02, Kriti Godey<notifications@github.com> a écrit :   
Yes, go ahead

**Comment by chimenekouomogne** [comment]
![Capture](https://user-images.githubusercontent.com/54715600/67736964-d95e5b00-fa09-11e9-9293-eb8d57d2e853.JPEG)
![Capture2](https://user-images.githubusercontent.com/54715600/67736967-da8f8800-fa09-11e9-9c7c-c5689c374c4e.JPEG)

**Comment by chimenekouomogne** [comment]
Hi @kgodey ! I thought that generate new author were about something like that. But i discovered that it is already available through admin interface. Now ,i don't know whether i should create a link to a page  that allows an author to fill its informations directly and to involve category. please Ma i'm a bit confused , need your help .

**Comment by kgodey** [comment]
@chimenekouomogne We don't always use the Lektor admin interface to write posts. When a new blog post entry is created with an unknown author username in the `author` field (e.g. if this entry was created and there was no `makkoncept` author file present), it would be great for the corresponding author folder and file (like [here](https://github.com/creativecommons/creativecommons.github.io-source/tree/master/content/blog/authors/makkoncept) to get created automatically. Only the username field can be automatically created, the rest of the fields should not be present.

**Comment by chimenekouomogne** [comment]
![code](https://user-images.githubusercontent.com/54715600/67901838-0f195600-fb68-11e9-960a-dc07e2684fba.JPEG)
![code2](https://user-images.githubusercontent.com/54715600/67901841-12144680-fb68-11e9-8f20-cb3e3d29af49.JPEG)
Hi @kriti ! I have modified the file author.html so that when you want to create a new blog post, you can only enter your username in the file.lr

**Comment by chimenekouomogne** [comment]
![result](https://user-images.githubusercontent.com/54715600/67902482-97e4c180-fb69-11e9-8a9e-d25336fd4762.JPEG)
![reult2](https://user-images.githubusercontent.com/54715600/67902484-987d5800-fb69-11e9-8d58-ff224485947d.JPEG)
Here are the results. As you can see, for a new author , only his username and post are display. For an old author, his name and his post are display. Please is that what you wanted me to do ?

**Comment by chimenekouomogne** [comment]
Hi @kgodey ! i have face too dificulties while making pull request to this site .  but i have done it on my github link :
https://github.com/chimenekouomogne/creativecommons.github.io-source.

**Comment by chimenekouomogne** [comment]
Hi @kgodey ! please here is a link for my final application :
https://docs.google.com/document/d/1Gr-xw99jg_wgqOXVNm4hd5lglhRS4trWqDWVFAXgnGA/edit?pli=1#

**Comment by kgodey** [comment]
hi @chimenekouomogne, sorry for the delay on getting back to you on this. Your work does not address this issue, but after thinking about it, I don't think this issue makes sense to implement at this time anyway.

We want people to be thoughtful about adding new authors and categories and this issue would automatically generate missing authors/categories, which would make errors harder to catch.

I'm going to close the issue.
