### ISSUE TITLE
Fix obvious style issues on mobile

### ISSUE THREAD

**Issue by hugosolar** [creativecommons/creativecommons.github.io-source#11]
There are a lot of obvious style issues when the site is viewed on mobile. Please document and fix them.

**Comment by Sgarg510** [comment]
The bootstrap template is pretty much fine. I added a meta view-port and made a pr as it was missing. That will fix it on the website.

**Comment by hugosolar** [comment]
PR https://github.com/creativecommons/creativecommons.github.io-source/pull/22 merged that add viewport meta
There are a lot of style issues to fix, though

**Comment by kgodey** [comment]
I narrowed the scope of this issue a little and I'll create a separate issue for setting up SASS.

**Comment by kgodey** [comment]
Created #26 for Sass.

**Comment by accakks** [comment]
Hi, I would like to work on this. 
I'll start by analyzing what style issues are there exactly and work on them. 

Is there anything you might like to add?

**Comment by kgodey** [comment]
The only one I can think of is the footer having overflowing text and whitespace below it when the screen is narrow enough for the text to not fit in the footer.
![Technology at Creative Commons — Creative Commons on GitHub](https://user-images.githubusercontent.com/287034/54054173-7f2d3300-41b7-11e9-90b2-f39479bc4687.png)

**Comment by accakks** [comment]
@kgodey Can you assign this to me or mark in progress?

**Comment by kgodey** [comment]
@accakks I can't assign to you since you're not in our GitHub organization, our [Contributing Code](https://creativecommons.github.io/contributing-code/) guidelines mentions that if there's a comment on the issue saying someone is working on it, other people shouldn't work on it so you should be good.

**Comment by sgrepos** [comment]
@kgodey this is not showing up as "in progress" currently, although I know you just recently updated that inside the contribution guidelines. I'm just commenting here to express my interest in working on it, in case it might be available!

@accakks can you update us and let us know if you're still working on this? :)

**Comment by accakks** [comment]
@sgrepos Yes I'll be working on this. If I'm not able to I'll let you know in 2-3 days.

**Comment by sgrepos** [comment]
@accakks Alright, great! 👍

**Comment by kgodey** [comment]
@sgrepos I haven't updated any existing issues with the label yet, let me know if there are more I should update.

**Comment by accakks** [comment]
@kgodey I have created a PR #36  fixing text and whitespace overflow issue. 
Do you think I should take time to explore and fix other mobile issues (if any) on the PR or I should create other PR(s) of other issues if found?

**Comment by kgodey** [comment]
@accakks that would be great, @hugosolar may have other specific examples of things to fix too.
