### ISSUE TITLE
Custom 404 page

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/creativecommons.github.io-source#131]
**Is your feature request related to a problem? Please describe.**
The current GitHub site gives the default 404 when one visits a [non-existent page](https://opensource.creativecommons.org/nonexistent).

**Describe the solution you'd like**
Since GitHub Pages support [custom 404 pages](https://help.github.com/en/github/working-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site), we should probably have one.

**Comment by techievivek** [comment]
@kgodey i would like to work on this.
Thank you

**Comment by kgodey** [comment]
@techievivek go ahead! Please post your design on your pull request for feedback.

**Comment by techievivek** [comment]
@kgodey could you please help me which one is better and should I add some important links in case the user would like to navigate once they are lost.
# First one
![error-404-2](https://user-images.githubusercontent.com/35863227/69204968-9574f680-0b6e-11ea-8edb-061ddfaa8fc2.png)
# Second one
![error-404-1](https://user-images.githubusercontent.com/35863227/69204969-960d8d00-0b6e-11ea-8983-77a8a8b07f44.png)

**Comment by techievivek** [comment]
@kgodey  mam please respond so that i can proceed further.
Thank you.

**Comment by dhruvkb** [comment]
@techievivek if I may interject, I just want to make sure that you're using CSS for creating these designs and not images, because they may not scale that well. Even if you're using SVGs, they won't achieve the level of interactivity or internationalisation as HTML content which can be manipulated using JS or translated based on user locale.

**Comment by techievivek** [comment]
@dhruvkb yes i am using HTML, CSS for the design(no images are used), but in first one the shapes has been created using svg, and the second one is just HTML,CSS & JS without svg.
So please tell me should i go with first one(it is completely responsive).

**Comment by dhruvkb** [comment]
That decision is upto @kgodey. I just wanted to alleviate my concerns. She will respond once work resumes in [her TZ](https://www.timeanddate.com/worldclock/usa/ohio). Feel free to contribute to other open issues in the meantime!

**Comment by techievivek** [comment]
I have added SVG image as a placeholder(showing 404 error) which is completely responsive for all the devices, please check it.

**Comment by kgodey** [comment]
hey @techievivek, sorry for the delay in responding. Your designs are good but we'd like a really simple/clean page that matches the rest of the site. It would be ideal if you could show the header and footer of the site as well.

Some examples along the lines of what I was thinking of (but with the header and footer added):
https://egyptianstreets.com/wp-content/uploads/2017/07/404.jpg
https://www.yo-kart.com/blog/wp-content/uploads/2018/01/404-Page-not-found.jpg

Also, please make sure to use CC's brand colors: https://creativecommons.org/2019/10/30/cc-style-guide/

**Comment by techievivek** [comment]
@kgodey This is what i have **PR**  and as a placeholder i am using **SVG image** with the same theme color as CC's brand color.(It is completely responsive and i have testesd it for different browser size).
# Navbar part
![header](https://user-images.githubusercontent.com/35863227/69592273-761d1400-101b-11ea-80e5-f2b266bfa64f.png)
# Footer Part
![footer](https://user-images.githubusercontent.com/35863227/69592281-7d442200-101b-11ea-90ae-36c36bd06792.png)

**Comment by techievivek** [comment]
@kgodey it contains a link(Return Home) to redirect user to the Hompeage.

**Comment by kgodey** [comment]
Hi @techievivek. The header and footer looks good! Please remove the image and just use text for the "404" part. Thanks!

**Comment by techievivek** [comment]
@kgodey i have initiated a new **PR** with the design suggested by you, i am attaching a demo image for the same. Please check it and let me know if there is anything i can improve upon.
Thank you.
![404-custom](https://user-images.githubusercontent.com/35863227/69816076-a8965f00-121d-11ea-9fe0-ee25f2310704.png)

**Comment by dhruvkb** [comment]
@techievivek sorry for these incremental iterations but why the green shadows? Also the frown emoji looks out of place.

**Comment by techievivek** [comment]
Ok...thank you for the suggestions. I will change accordingly.
Can you kindly let me know if I should also remove the shadow completely or just change the color to black.

**Comment by dhruvkb** [comment]
Black would look good.

**Comment by techievivek** [comment]
@dhruvkb @kgodey i have updated as suggested and initiated a new **PR** , i am also attaching a demo image for the same. 
![custom-404](https://user-images.githubusercontent.com/35863227/69871450-d42a4f80-12d8-11ea-8df7-d3048a4770b9.png)
If there is anything else i can improve upon please suggest.
Thank you.
