### ISSUE TITLE
Poor mobile readability

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/creativecommons.github.io-source#146]
## Describe the bug
On vertical screens of a certain size, the text snaps to the left side of the screen and leaves a big margin on the right, making the text harder to read and the images much smaller.

## To Reproduce
You can reproduce this by viewing the blog on a mobile phone or by changing the window size on your desktop.

## Screenshots
![Here's how it looks on my mobile](https://i.imgur.com/wSwZWN1.jpg)

**Comment by techievivek** [comment]
@kgodey hello mam, if no one is working on this then i would like to work on this.
Thank you.

**Comment by kgodey** [comment]
Go ahead

**Comment by techievivek** [comment]
@kgodey mam i have fixed the bug and also changed the **text-align to justify **, please have a look and tell me if there is anything else i can improve upon.
Thank you.

**Comment by techievivek** [comment]
@kgodey hello mam, actually I have merged the branches(master and blog series one), so whenever i am trying to PR for poor mobile readability issue it is taking content from both the branches. I am not getting any clue to resolve this, please help me or else once you will verify the blog series one i will add poor mobile readability PR.
Thank you.

**Comment by kgodey** [comment]
@techievivek I'd advise creating a new branch off of current `master` and recreating the changes.

You can also try rebasing your commits for poor mobile readability onto the current `master` branch and pushing that rebased branch. https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by techievivek** [comment]
@kgodey thank you mam, i will try it.

**Comment by techievivek** [comment]
@kgodey hello mam Thank you and I have created the PR as you advised, please have a look.
Thank you
