### ISSUE TITLE
Footer styling issues

### ISSUE THREAD

**Issue by kgodey** [creativecommons/creativecommons.github.io-source#15]
Two issues:

1. The footer should show up at the bottom of the viewport when the content doesn't go until the bottom but even for pages without much content, you need to scroll to see the footer.
<img width="2032" alt="screen shot 2019-02-22 at 9 26 48 pm" src="https://user-images.githubusercontent.com/287034/53280510-cf50c380-36e8-11e9-8d50-2fea1025ebc3.png">
2. When the viewport is narrow enough that the CC license text takes up 2 lines instead of 1, there is a white gap between the bottom of the page and the footer.

![contributing code creative commons on github](https://user-images.githubusercontent.com/287034/53280519-e98aa180-36e8-11e9-8a21-1abf8b77bda5.png)

![technology at creative commons creative commons on github](https://user-images.githubusercontent.com/287034/53280522-eb546500-36e8-11e9-9feb-de28e4d8db37.png)

**Comment by hugosolar** [comment]
Fixed in https://github.com/creativecommons/creativecommons.github.io-source/commit/543b1b189a8ec52cc661aabf544e5243c4d121cc
