### ISSUE TITLE
Fix issue where :warning: shows up on Projects page on CC Open Source instead of emoji

### ISSUE THREAD

**Issue by hugosolar** [creativecommons/creativecommons.github.io-source#161]

**Comment by hugosolar** [comment]
We can add a javascript plugin to replace the emoji shortcodes 
I've found [Js-emoji](https://github.com/iamcal/js-emoji) which uses the default browser support for Emojis
What do you think about that @kgodey ?

**Comment by hugosolar** [comment]
@kgodey could you please share to me the python script who generates the project list to use it this [Emoji library](https://pypi.org/project/emoji/)
As we talk, is a better approach to solve the problem

**Comment by kgodey** [comment]
@hugosolar uploaded here: https://github.com/creativecommons/ccos-scripts/tree/master/generate_projects_page

**Comment by JuanitoAlimana** [comment]
Cut it.

Sent from iPhone

> El 21/02/2020, a las 17:49, Kriti Godey <notifications@github.com> escribió:
> 

﻿
Closed #161 via creativecommons/ccos-scripts#3.
