### ISSUE TITLE
GSoC project ideas page should allow selection of both difficulty level and a tool of choice

### ISSUE THREAD

**Issue by Gbahdeyboh** [creativecommons/creativecommons.github.io-source#169]
## Problem Description
On the GSoC project Ideas page, a visitor can select **only one** of the following seven categories to sort out project ideas of interest

- All Projects
- Difficulty: Easy
- Difficulty: Medium
- Difficulty: Hard
- Skill: JavaScript
- Skill: Python
- Skill: WordPress

[https://opensource.creativecommons.org/gsoc-2019/project-ideas/difficulty-easy/](https://opensource.creativecommons.org/gsoc-2019/project-ideas/difficulty-easy/)

But Ideally, there are 2 categories there;

- Difficulty Level
- Skill/Tool of choice

Only the selection of one of them can be done at a time. A beginner in JavaScript can not select the **Difficulty: Easy** category and the **Skill: JavaScript** together. 

## Solution Description
A visitor to the page should be able to select 2 categories which should be a **Difficulty Level** and a **Skill/Tool of choice** so users can sort out project ideas with the technology of interest and appropriate difficulty level that matches the user's level of proficiency.

**Comment by kgodey** [comment]
The GSoC project ideas page is no longer up, but we have a new project ideas page with the same issue: https://opensource.creativecommons.org/internships/project-ideas/

**Comment by Gbahdeyboh** [comment]
Thanks for the update @kgodey.

It would also be nice to be able to select multiple skills. There are projects that require knowledge of both python and JavaScript to complete.

**Comment by techievivek** [comment]
@kgodey I will like to try to implement this feature if no one is working on it. This feature will be really handy if implemented.
Thank you

**Comment by kgodey** [comment]
Go ahead @techievivek

**Comment by techievivek** [comment]
@kgodey Mam can you please tag the developer who has implemented this feature, as this seems tough with the current directory structure and given code logic.
Because suppose a person has clicked on a difficulty level now we will show them **two different links **
like https://opensource.creativecommons.org/internships/project-ideas/difficulty-easy/ so that he can choose another difficulty level and another type of link like https://opensource.creativecommons.org/internships/project-ideas/difficulty-hard/skill-javascript/ so that he can navigate to the project-ideas that are **hard and requires skill Javascript**.
We may need to alter the directory structure.

**Comment by kgodey** [comment]
I implemented this feature. 
Under the current implementation, we would have to generate a new page for every single combination of filters, which will probably get infeasible. The better way is probably to scrap the current implementation and implement filtering on the client side using JavaScript.

**Comment by pavitra14** [comment]
I would like to take up this issue if no one else is doing it. 
I can write up a logic on the client side javascript to filter things out.

**Comment by techievivek** [comment]
@pavitra14 please go ahead.

**Comment by techievivek** [comment]
@pavitra14 Also if you need any help, feel free to tag me.

**Comment by techievivek** [comment]
@kgodey @pavitra14 I think it will be better to make use of **current URL** the user is in.
There can be 3 cases:- 
1. If they are on **all**, on clicking any difficulty level or skill we can directly make them navigate to that page.
2. If they are on a particular difficulty level they can **either** navigate to all or to a skill, so accordingly we can do by looking at **href** of clicked link.
3. Similarly for skills.
We can have a class to all the links and then add listener and disable the deafult behaviour and check `current Url and target url` and redirect accordingly or filter records by using basic regex to get and match skill or difficulty.
All can be done in Plain Js without the need to alter anything in **content** folder.

**Comment by pavitra14** [comment]
@techievivek I do not intend them to navigate, I wanted to do it all from a single page.
Right now, I added data-filters to each button and assigned filter values to each idea via classes.
Rest is handled automatically via jQuery and Event handlers.
I did not need to edit the contents much, only had to add a filter-value variable in the model.
Also, the user must be able to selected multiple filters at once and should see the result instantly.
I did that only.

**Comment by techievivek** [comment]
@pavitra14 Yeah, I think this will be better, I suggested above one if you dont want to change anything in content folder.
Lets wait for @kgodey as she is one who implemented it.

**Comment by pavitra14** [comment]
@techievivek 
Also we will any how need to edit the **content** as the old redundant content needs to be removed.
Since we're showing everything on the front end, there's no need for the skill/difficulty category folders inside content anymore. 
This was requested in the review by @kgodey

**Comment by techievivek** [comment]
@pavitra14 Yes If we have to do everything in frontend then definitely we dont need any folder more.
I have seen your updated PR, its perfect.

**Comment by pavitra14** [comment]
Removed the redirect /internships/project-ideas/all 
Now the /internships/project-ideas/ is the root folder for all ideas.
Compatibility checked with lektor and can be easily managed via the admin backend.

**Comment by techievivek** [comment]
@pavitra14 perfect one👌

**Comment by Abhishek856** [comment]
hello , My self Abhishek mishra , I want to work on this issue.

**Comment by Abhishek856** [comment]
can i work on this

**Comment by pavitra14** [comment]
Kindly go through the issue, I've already sent a PR, writing tests is left, if you can do that, kindly checkout the linked PR.
