### ISSUE TITLE
Discrepancy in difficulty levels

### ISSUE THREAD

**Issue by monsij** [creativecommons/creativecommons.github.io-source#176]
The filter menu at [project idea page](https://opensource.creativecommons.org/internships/project-ideas/all/) mentions difficulty levels as **Easy, Medium and Hard**. On the other hand, the ideas mentioned are classified as having difficulty either **Low, Medium or High**.  I am not sure if [Easy,Low] , [Hard, High] are to be treated separately. Otherwise, this might be a bug.

**Comment by kgodey** [comment]
It's a bug, the difficulty should match the filters. Low should be renamed to Easy and High should be renamed to Hard.

**Comment by monsij** [comment]
I'm up for it @kgodey
