### ISSUE TITLE
CC Open Source Redesign

### ISSUE THREAD

**Issue by annatuma** [creativecommons/creativecommons.github.io-source#189]
## Problem Description / Context
Starting in 2019, Creative Commons began developing a design framework for use across CC web products. During Q1 of 2020, we expect to have the first complete version of the design library (known as Vocabulary), ready for use in future designs, and redesigns of existing products.

By the end of 2020, the goal of the Tech & Product team at Creative Commons is that all CC web products have a consistent design.

For the CC Open Source website, analytics indicate that there is a high bounce rate, and users spend a short time on specific pages, where ideally we are spurring action, such as the pages around contributing code and current projects. The information that currently exists on the site is in some cases presented in a confusing way.

## Solution Description / Main Goal
The goal of this project is to redesign all pages of the current site, using existing content, to improve user experience. The redesign must use Vocabulary and the Design Library in Figma.
Please note that no content (i.e. written word) changes are part of this project, this involves only the redesign of existing content.

If there is a need for design components that are not currently defined in CC’s Design Library, the designer is encouraged to make suggestions for addition to the Design Library, to be reviewed by CC’s product team.

## Workflow
The designer should not move between numbered steps without consultation with and sign-off by the CC product team. The designer must meet with the product team prior to tackling each subsequent step.

The project should be tackled in the following process:

1. Develop a wireframe of the homepage
2. This proposal should include changes to the content layout
3. Develop wireframes for other pages on the site
4. Create a high-fidelity mockup of the homepage, using the Figma Design Library
5. Create high-fidelity mockups of other pages on the site, using the Figma Design Library

## Success & Deliverables
Success in this project is defined by mockups in Figma being approved by CC’s product team.

## Resources & Supporting Links
The designer will have access to CC’s Figma account, as an editor.
Figma Design Library: https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A1

Vocabulary Repo: https://github.com/creativecommons/vocabulary

Vocabulary Storybook: https://cc-vocabulary.netlify.com/storybook/?path=/story/vocabulary-welcome--welcome

## Next Steps
Upon successful completion of the redesign, the user is invited to implement the design changes directly. If that work moves forward separate tickets will be created.

**Comment by panchovm** [comment]
It looks perfect

**Comment by pranshuls12** [comment]
Can I work on this ?

**Comment by Dhruvi16** [comment]
Looks great!

**Comment by annatuma** [comment]
This is currently being worked on by @Dhruvi16 with oversight from myself and @panchovm. Thank you for your interest @pranshuls12, please look for other tickets open to community contribution. You're also welcome to tackle https://github.com/creativecommons/vocabulary/issues/151

**Comment by kgodey** [comment]
This is live!
