### ISSUE TITLE
Link gives 404 error in the project ideas page.

### ISSUE THREAD

**Issue by Parimal7** [creativecommons/creativecommons.github.io-source#190]
## Describe the bug
The project listed [here](https://opensource.creativecommons.org/internships/project-ideas/all/#legal-database) has a broken link. Under sub-heading "The Problem", the third bullet point "It does not use Vocabulary, CC’s new web design system.", Vocabulary hyperlink gives error 404.

## To Reproduce
1. Go to ['project ideas page'](https://opensource.creativecommons.org/internships/project-ideas/all/#legal-database)
2. Click on Vocabulary under sub-heading "The Problem", bullet point 3.
3. See error.

## Expected behavior
The link should probably point to https://cc-vocabulary.netlify.com/?path=/story/vocabulary--welcome?

## Desktop (please complete the following information)
 - OS: Ubuntu 18.04
 - Browser: Google Chrome
 - Version 80.0.3987.122

**Comment by Parimal7** [comment]
If possible can I solve this issue ? I am already assigned to another issue but stuck atm due to building problems so may I solve this in the mean time?

**Comment by nnadidan360** [comment]
i would love to fix this issue and i also need to get the source code for the page

**Comment by kgodey** [comment]
The link should point to https://cc-vocabulary.netlify.com/.

Assigning to @Parimal7 since they expressed interest first.
