### ISSUE TITLE
Github repo link on top left corner is not clickable on mobile devices.

### ISSUE THREAD

**Issue by techievivek** [creativecommons/creativecommons.github.io-source#191]
## Describe the bug
GitHub repository link for CC opensource website is not clickable on mobile devices and thus donot redirect to CC opensource website GitHub repo. And also the design can be changed a bit as it is almost unrecognisable as GitHub logo.

## To Reproduce
1. Open the site in mobile.
2. Try clicking on the top left corner (github icon).
3. It doesn't responds to click.

## Expected behavior
It must redirect to CC opensource website repository.

## Screenshots
![Screenshot_20200302-205145](https://user-images.githubusercontent.com/35863227/75689820-d9c47680-5cc7-11ea-93fc-ab58d35ea34d.jpg)

## Smartphone (please complete the following information)
 - Device: One plus 7T
 - OS: Android 10
 - Browser: Chrome
 - Version (ex. 22)

## Additional context
Design for small devices can be changed a bit as it is almost unrecognisable as GitHub logo.

**Comment by harsh551** [comment]
Hey, I want to work on this issue if this is available.

**Comment by kgodey** [comment]
Go ahead. Please don't change the design though.
