### ISSUE TITLE
Spelling error in https://opensource.creativecommons.org/community/

### ISSUE THREAD

**Issue by terrifricker** [creativecommons/creativecommons.github.io-source#198]
## Describe the bug
In the list of slack channels, on page
https://opensource.creativecommons.org/community/
there is a missing 'l' in toolkit in the link to 'CC Platform Tookit'

## To Reproduce

1. Go to https://opensource.creativecommons.org/community/
2. Scroll down to the Slack channels table.
3. In the third entry from the bottom
4. The link to the #cc-outreachy-platform-toolkit that is in the right column is misspelled.  An 'l' needs to be added to change 'tookit' to 'toolkit'

## Screenshots
![Screen Shot 2020-03-06 at 10 36 15 AM](https://user-images.githubusercontent.com/51532684/76112555-44f79c80-5f97-11ea-9337-dcba1f22964a.png)

## Desktop (please complete the following information)
 - OS: macOS Mojave Version 10.14.6
 - Safari
 - Version 13.0.4

**Comment by terrifricker** [comment]
I would like to be assigned to this issue.

**Comment by dhruvkb** [comment]
@terrifricker please go ahead and submit a PR fixing it.
