### ISSUE TITLE
Github Corner Icon overshadow the CC logo in small screen devices.

### ISSUE THREAD

**Issue by techievivek** [creativecommons/creativecommons.github.io-source#229]
## Describe the bug
The GitHub corner icon in the navbar overshadows the CC logo in small screen devices.

## To Reproduce

1. Go to CC open-source website on a smartphone.
2. It will be visible that GitHub corner overshadows CC logo.

## Expected behavior
There must be a bit space between both the images and shouldn't overlap.

## Screenshots
![github icon shadows CC logo](https://user-images.githubusercontent.com/35863227/79036689-65df8d00-7be8-11ea-8f54-7a4115f05310.png)

## Desktop (please complete the following information)
 - OS: Ubuntu 18.04
 - Browser: Firefox

## Smartphone (please complete the following information)
 - Device: One plus 7t
 - OS:Android
 - Browser: Chrome

## Additional context
For small screen devices we can give a margin-left and this will solve the issue, I am adding a PR for the same.

**Comment by hugosolar** [comment]
We consider the Github Corner over the CC logo make sense
So this is not an issue
