### ISSUE TITLE
Indentation errors in "How to Contribute" section on Community Teams page

### ISSUE THREAD

**Issue by akmadian** [creativecommons/creativecommons.github.io-source#237]
## Describe the bug
There are some indentation errors in the "How to Contribute" section in the Community Teams page. Some lines are not indented, when they should be indented by one level. See the attached screenshot, the lines that are highlighted should be indented one level deeper.

## To Reproduce

1. Go to https://opensource.creativecommons.org/community/community-teams/#how-to-contribute
2. See error

## Screenshots
![image](https://user-images.githubusercontent.com/28791774/80535062-0ce85680-8955-11ea-893f-2dcc8260bbb1.png)

## Desktop (please complete the following information)
 - OS: Windows 10 Pro 1909
 - Browser: Firefox Dev. Ed. 76.0

## Additional context

[The Community Teams content file](https://github.com/creativecommons/creativecommons.github.io-source/blob/master/content/community/community-teams/contents.lr)

**Comment by SaurabhAgarwala** [comment]
I will work on this.

**Comment by SaurabhAgarwala** [comment]
I have identified three more bugs on this page and bring them to notice and correct them as well.

1. I think the words `Community Contribuotor` and `Community Collaborator`were supposed to be bolded but it isn't and instead is getting reflected as embedded in double asterisks(**).  
![Not Bolded](https://user-images.githubusercontent.com/32371951/80588389-e6e6b300-8a35-11ea-9ec8-c38c3c7a335e.png)  

2. The ordered numbering list in the below shown two places is getting rendered incorrectly.   

![Improper Numbering](https://user-images.githubusercontent.com/32371951/80588886-cc610980-8a36-11ea-8475-d704e00de321.png)

![Improper Numbering 2](https://user-images.githubusercontent.com/32371951/80589019-06caa680-8a37-11ea-9157-56473ba11080.png)  

3. The nested bullets should have a different style to demarcate. This should  be made consistent with the nested bullet-style present in the other parts of this page.  

![Improper Nested Bullets Style](https://user-images.githubusercontent.com/32371951/80589452-d7686980-8a37-11ea-802b-2cab12e08e4c.png)
