### ISSUE TITLE
Add Slack channels to project list on Projects page

### ISSUE THREAD

**Issue by kgodey** [creativecommons/creativecommons.github.io-source#241]
## Description
Our Projects page should include the Slack channel for projects, if they have one.
https://opensource.creativecommons.org/contributing-code/projects/

## Additional context
This will also entail updating the CC metadata YAML file in repos to include the Slack channel information and updating the data gathering script (https://github.com/creativecommons/ccos-scripts/tree/master/generate_projects_page) to use that data.

**Comment by kgodey** [comment]
This was suggested by @obulat.

**Comment by theprover97** [comment]
@kgodey Here are some slack channels that I found for the projects.
# cc-dev-license-chooser,  # cc-dev-linkchecker,   # cc-dev-catalog,   # cc-dev-cc-catalog-viz,   # cc-dev-browser-extension,   # cc-certificates,   # cc-search,   # cc-dev-vocabulary.
Can i code them to include in the projects?
