### ISSUE TITLE
Convert HTML tables to Markdown tables

### ISSUE THREAD

**Issue by kgodey** [creativecommons/creativecommons.github.io-source#248]
## Overview
Now that we have tables styled by default in [Add default styling for tables by sp35 · Pull Request #227 · creativecommons/creativecommons.github.io-source](https://github.com/creativecommons/creativecommons.github.io-source/pull/227), we should replace instances of HTML tables with tables formatted in Markdown wherever possible. It will make things more readable.

## Notes on PRs
Feel free to send PRs for one table at a time. Please make sure to include before and after screenshots in your PRs.

## Files with HTML Tables
- [ ] [`content/blog/entries/cc-vocabulary-the-main-course/contents.lr`](https://github.com/creativecommons/creativecommons.github.io-source/blob/master/content/blog/entries/cc-vocabulary-the-main-course/contents.lr)
- [ ] [`content/community/contents.lr`](https://github.com/creativecommons/creativecommons.github.io-source/blob/master/content/community/contents.lr)
- [x] [`content/internships/contents.lr`](https://github.com/creativecommons/creativecommons.github.io-source/blob/master/content/internships/contents.lr)

(Be sure to check  for activity below)

**Comment by bhavybarca** [comment]
Working on this issue.

**Comment by ayu023ban** [comment]
Want to work on this issue. I will update other two tables
