### ISSUE TITLE
Fix or improve styling for active nav links when navbar has collapsed.

### ISSUE THREAD

**Issue by kgodey** [creativecommons/creativecommons.github.io-source#25]
**I'm submitting a...**
- [x] Bug

**Description:**
The styling for the active nav item looks fine when the nav is expanded (see blue box in screenshot)
![active link full size](https://user-images.githubusercontent.com/287034/53930840-d967b000-4060-11e9-875b-1d2bf39b7318.png)

When the nav is collapsed, the border beneath the active item occupies the entire width of the header.
![active link collapsed](https://user-images.githubusercontent.com/287034/53930860-f43a2480-4060-11e9-92ef-701a6f61b04c.png)

Feel free to change the active link styling if desired. One way to fix it may be to use similar styling to the https://creativecommons.org website (see "Use & remix" nav styling in https://creativecommons.org/use-remix/).

**Comment by makkoncept** [comment]
hi @kgodey, can I work on this issue?

Thanks

**Comment by kgodey** [comment]
The media query was missing an end curly brace and broke the ToC styling, I fixed it in https://github.com/creativecommons/creativecommons.github.io-source/commit/1558da38608103239ed81178559e8902a9e6a8d4

<img width="1982" alt="Screen Shot 2019-03-08 at 3 59 00 PM" src="https://user-images.githubusercontent.com/287034/54055952-9c183500-41bc-11e9-94d0-bff43a8ca4b3.png">

**Comment by makkoncept** [comment]
Sorry I didn't noticed it.
