### ISSUE TITLE
Fix typos and grammatical errors 

### ISSUE THREAD

**Issue by rajat2502** [creativecommons/creativecommons.github.io-source#251]
There are some grammatical errors in the `/internships/applicant-guide/` page that needs to be fixed.

- ![image](https://user-images.githubusercontent.com/42200276/81664814-7f7d2a00-945d-11ea-8979-978e9b158ae3.png) 
Should be `contacting` in place of `contact`.

- ![image](https://user-images.githubusercontent.com/42200276/81664921-a6d3f700-945d-11ea-9a2c-60918594770b.png) 
Should be `Also,` in place of `Also`.

- Also, we can replace `open source` with `open-source`.

**Comment by kgodey** [comment]
@rajat2502 thank you for reporting these. Please go ahead and fix the first two issues you mentioned.

Re: "open source", we prefer to use it unhyphenated.

**Comment by rajat2502** [comment]
Sure, I will make a PR to fix both of them.

**Comment by rajat2502** [comment]
Hey @kgodey, I am not able to make a pull request, I think the rights are disabled right now.
![image](https://user-images.githubusercontent.com/42200276/81711923-ba00ba00-9491-11ea-9fb4-71601247509f.png)

**Comment by fakela** [comment]
@rajat2502 are you sending in a PR for this

**Comment by rajat2502** [comment]
@fakela Yeah, I just made a PR for the same.
