### ISSUE TITLE
Fix grammatical errors in README

### ISSUE THREAD

**Issue by rajat2502** [creativecommons/creativecommons.github.io-source#252]
There are some errors in `README` file
- ![image](https://user-images.githubusercontent.com/42200276/81712489-46ab7800-9492-11ea-8ad1-9a523ea497fa.png)
`is` should be replaced by `are`.

-  ![image](https://user-images.githubusercontent.com/42200276/81712687-896d5000-9492-11ea-934d-584dcb76497b.png)
Should be `in the` in place of just `in`.

**Comment by chetan-v** [comment]
Hi I want to do that

**Comment by kgodey** [comment]
(1) "CSS" is singular, so it should be "is." Please leave it as-is.
(2) Yes, it should be "in the" instead of "in".

**Comment by rajat2502** [comment]
Should I make a PR for the same?

**Comment by kgodey** [comment]
sure
