### ISSUE TITLE
Fix typos and grammatical errors on Code of Conduct page

### ISSUE THREAD

**Issue by pranay-ar** [creativecommons/creativecommons.github.io-source#256]
There are two grammatical errors in the /community/code-of-conduct/  page that needs to be addressed.

_In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to **making** participation in our project and our community a harassment-free experience for everyone...._

- Should be **make** instead of **making**  (the verb form was used wrong here.)

_Instances of abusive, **harassing, or** otherwise unacceptable behavior may be reported by contacting the project team at conduct@creativecommons.org._

- Should be **harassing or** instead of **harassing, or**. There is no need for a comma before or.

**Comment by chetan-v** [comment]
@pranay-ar I wanna work on it

**Comment by kgodey** [comment]
@pranay-ar @chetan-v these are both not errors. "making" is perfectly valid in that context, and the comma there is the Oxford comma. We're also using the Contributor Covenant verbatim and don't want to make any changes to it since it's a widely used document.
