### ISSUE TITLE
Port CSS to SASS 

### ISSUE THREAD

**Issue by kgodey** [creativecommons/creativecommons.github.io-source#26]
**I'm submitting a...**
- [x] Feature request

**Description:**
There is some CSS in the `/assets/` folder. We'd like to use modern best practices and move to the Sass extension language. We also want to build CSS from the Sass file(s) automatically during the Lektor build process.

**Resources**
- [Sass documentation](https://sass-lang.com/documentation/file.SASS_REFERENCE.html)
- [Lektor guide to using Webpack to build CSS from Sass](https://www.getlektor.com/docs/guides/webpack/)

**Comment by sanjana11147** [comment]
Hii @kgodey. I would like to work on this issue. Can you assign it to me? 🙂

**Comment by kgodey** [comment]
@sanjana11147 feel free to work on it!

**Comment by code-n-chill** [comment]
Hi @kgodey , please check the pull request and let me know if there is anything to be fixed.  :-)

**Comment by kgodey** [comment]
Reopening since #31 was reverted.

**Comment by code-n-chill** [comment]
@kgodey, the last PR broke up the styling because i forgot to build the project before the commit and there was no css file present in the repo. I have built the project this time before hand and had taken utmost care of are not to miss anything this time. Sorry for what happened in the last PR.

**Comment by kgodey** [comment]
@code-n-chill don't worry about it! I've reviewed your PR.
