### ISSUE TITLE
Incorrect link to Community Team Page on Community Team Members

### ISSUE THREAD

**Issue by sp35** [creativecommons/creativecommons.github.io-source#260]
## To Reproduce

1. Go to [Community Team Members](https://opensource.creativecommons.org/community/community-team/members/)
2. Look at For more information about CC Community Team, please see [the Community Team Page](https://opensource.creativecommons.org/content/community/community-teams/).

## Expected behavior

Change the URL to point at https://opensource.creativecommons.org/community/community-team/

## Screenshots

![Screenshot from 2020-05-19 06-52-27](https://user-images.githubusercontent.com/51958314/82274293-63b5de80-999d-11ea-837f-c48dc031232c.png)
![Screenshot from 2020-05-19 06-52-33](https://user-images.githubusercontent.com/51958314/82274304-6d3f4680-999d-11ea-8762-66ae41234db5.png)

**Comment by kgodey** [comment]
Thanks for spotting this, @sp35

**Comment by chetan-v** [comment]
@sp35 @kgodey I wanna do that

**Comment by sp35** [comment]
@chetan-v Go ahead!

**Comment by chetan-v** [comment]
@sp35  I tried but unable to find that link

**Comment by sp35** [comment]
> @sp35 I tried but unable to find that link

From this [page's contents](https://github.com/creativecommons/creativecommons.github.io-source/blob/master/content/community/community-team/members/contents.lr), I could find that the template name is `community_team_list.html`

Heading to [community_team_list.html](https://github.com/creativecommons/creativecommons.github.io-source/blob/master/templates/community_team_list.html), I see the HTML for the page.

[Here](https://github.com/creativecommons/creativecommons.github.io-source/blob/fcd581a2213e86f376fd39ecebf5cec47547a00e/templates/community_team_list.html#L5) you'll have to replace the URL, 
from `/content/community/community-teams/`
to `/community/community-team/`

Thanks for trying @chetan-v , please submit a pr.

**Comment by chetan-v** [comment]
@sp35  In my repo there is no community_team_list.html

I clone it again but nothing happens
![creativecommons github io-source_templates at master · chetan-v_creativecommons github io-source - Google Chrome 21-05-2020 10_28_59](https://user-images.githubusercontent.com/63091769/82525061-1af15780-9b4e-11ea-83e6-2aab86dea431.png)


that's

**Comment by sp35** [comment]
Closing this manually as it was not closed by #269
