### ISSUE TITLE
Add link to Usability page on CC Search page

### ISSUE THREAD

**Issue by annatuma** [creativecommons/creativecommons.github.io-source#268]
At the bottom of the CC Search page we reference our forthcoming Usability page.

Once https://github.com/creativecommons/creativecommons.github.io-source/issues/267 is complete, we need to update the CC Search page to update the text at the bottom of the page and add the link in.

Note: this ticket is blocked until https://github.com/creativecommons/creativecommons.github.io-source/issues/267 is done.

**Comment by sp35** [comment]
Now, this can be unblocked :)

**Comment by kgodey** [comment]
done, thanks!

**Comment by ritesh-pandey** [comment]
Can I take this up?

**Comment by sp35** [comment]
Sure @ritesh-pandey

**Comment by ritesh-pandey** [comment]
If I understand correctly, updated text will be

Visit our [Usability page](/contributing-code/usability/) for more details on how to participate.

**Comment by sp35** [comment]
Yes @ritesh-pandey
