### ISSUE TITLE
Change Slack channel of cccatalog project on Community page

### ISSUE THREAD

**Issue by krysal** [creativecommons/creativecommons.github.io-source#270]
## Describe the bug
Currently the Community page points to `#cc-search` for the [Catalog](https://github.com/creativecommons/cccatalog) project, when it actually has its own channel: `cc-dev-catalog`.

## Expected behavior
Indicate the correct Slack channel for the [CC Catalog](https://github.com/creativecommons/cccatalog).

**Comment by ariessa** [comment]
Hi, I've fixed the issue and created pull request #275
