### ISSUE TITLE
Deployment errors on add_vocabulary branch.

### ISSUE THREAD

**Issue by Dhruvi16** [creativecommons/creativecommons.github.io-source#296]
## Description

The `add_vocabulary` is deployed [here](https://cc-open-source-dev.netlify.app/). But there are errors in the deploy log. One of them is  - `(jinja2.exceptions.UndefinedError: 'check_file' is undefined)`
 
## Reproduction

I am unable to reproduce it on local but the log can be found [here](https://app.netlify.com/sites/cc-open-source-dev/deploys/5ede87b71b201d00083dce4e)

## Environment

 - Device: (laptop)
 - OS: (ubuntu)
 - Browser: ( Firefox)
 - Version: (75.0)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Dhruvi16** [comment]
https://github.com/lektor/lektor/pull/467#issuecomment-337728860 - I found this.

But I am not sure I understand it correctly or is it of any use to us. @kgodey @makkoncept any thoughts?

**Comment by makkoncept** [comment]
@Dhruvi16 I also didn't understood the comment but can you try running the command `lektor plugin list`? This will show all the installed plugins and maybe `check_file` was not installed. You can then run `lektor plugin reinstall` to reinstall all the plugins.

Actually I am facing another problem while debugging this. I was not able to reproduce the error on `master` and therefore cloned the repo again. But, now even `pipenv install` command is failing for me. 

<details> <summary> Error Log </summary>
 creativecommons.github.io-source (master) pipenv install

Installing dependencies from Pipfile.lock (b44b97)…
Failed to load paths: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils.sysconfig'

Output: 
Failed to load paths: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils.sysconfig'

Output: 
Failed to load paths: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils.sysconfig'

Output: 
An error occurred while installing babel==2.8.0 --hash=sha256:1aac2ae2d0d8ea368fa90906567f5c08463d98ade155c0c4bfedd6a0f7160e38 --hash=sha256:d670ea0b10f8b723672d3a6abeb87b565b244da220d76b4dba1b66269ec152d4! Will try again.
An error occurred while installing certifi==2019.11.28 --hash=sha256:25b64c7da4cd7479594d035c08c2d809eb4aab3a26e5a990ea98cc450c320f1f --hash=sha256:017c25db2a153ce562900032d5bc68e9f191e44e9a0f762f373977de9df1fbb3! Will try again.
An error occurred while installing cffi==1.14.0 --hash=sha256:62ae9af2d069ea2698bf536dcfe1e4eed9090211dbaafeeedf5cb6c41b352f66 --hash=sha256:14491a910663bf9f13ddf2bc8f60562d6bc5315c1f09c704937ef17293fb85b0 --hash=sha256:2089ed025da3919d2e75a4d963d008330c96751127dd6f73c8dc0c65041b4c26 --hash=sha256:99f748a7e71ff382613b4e1acc0ac83bf7ad167fb3802e35e90d9763daba4d78 --hash=sha256:e577934fc5f8779c554639376beeaa5657d54349096ef24abe8c74c5d9c117c3 --hash=sha256:cef128cb4d5e0b3493f058f10ce32365972c554572ff821e175dbc6f8ff6924f --hash=sha256:7e63cbcf2429a8dbfe48dcc2322d5f2220b77b2e17b7ba023d6166d84655da55 --hash=sha256:cf16e3cf6c0a5fdd9bc10c21687e19d29ad1fe863372b5543deaec1039581a30 --hash=sha256:e56c744aa6ff427a607763346e4170629caf7e48ead6921745986db3692f987f --hash=sha256:3d311bcc4a41408cf5854f06ef2c5cab88f9fded37a3b95936c9879c1640d4c2 --hash=sha256:8c0ffc886aea5df6a1762d0019e9cb05f825d0eec1f520c51be9d198701daee5 --hash=sha256:028a579fc9aed3af38f4892bdcc7390508adabc30c6af4a6e4f611b0c680e6ac --hash=sha256:3b911c2dbd4f423b4c4fcca138cadde747abdb20d196c4a48708b8a2d32b16dd --hash=sha256:66e41db66b47d0d8672d8ed2708ba91b2f2524ece3dee48b5dfb36be8c2f21dc --hash=sha256:399aed636c7d3749bbed55bc907c3288cb43c65c4389964ad5ff849b6370603e --hash=sha256:8a6c688fefb4e1cd56feb6c511984a6c4f7ec7d2a1ff31a10254f3c817054ae4 --hash=sha256:c43866529f2f06fe0edc6246eb4faa34f03fe88b64a0a9a942561c8e22f4b71f --hash=sha256:001bf3242a1bb04d985d63e138230802c6c8d4db3668fb545fb5005ddf5bb5ff --hash=sha256:95cd16d3dee553f882540c1ffe331d085c9e629499ceadfbda4d4fde635f4b7d --hash=sha256:1cae98a7054b5c9391eb3249b86e0e99ab1e02bb0cc0575da191aedadbdf4384 --hash=sha256:b8c78301cefcf5fd914aad35d3c04c2b21ce8629b5e4f4e45ae6812e461910fa --hash=sha256:f2b0fa0c01d8a0c7483afd9f31d7ecf2d71760ca24499c8697aeb5ca37dc090c --hash=sha256:00789914be39dffba161cfc5be31b55775de5ba2235fe49aa28c148236c4e06b --hash=sha256:675686925a9fb403edba0114db74e741d8181683dcf216be697d208857e04ca8 --hash=sha256:337d448e5a725bba2d8293c48d9353fc68d0e9e4088d62a9571def317797522b --hash=sha256:c420917b188a5582a56d8b93bdd8e0f6eca08c84ff623a4c16e809152cd35793 --hash=sha256:cab50b8c2250b46fe738c77dbd25ce017d5e6fb35d3407606e7a4180656a5a6a --hash=sha256:2d384f4a127a15ba701207f7639d94106693b6cd64173d6c8988e2c25f3ac2b6! Will try again.
An error occurred while installing chardet==3.0.4 --hash=sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691 --hash=sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae! Will try again.
An error occurred while installing click==7.1.1 --hash=sha256:8a18b4ea89d8820c5d0c7da8a64b2c324b4dabb695804dbfea19b9be9d88c0cc --hash=sha256:e345d143d80bf5ee7534056164e5e112ea5e22716bbb1ce727941f4c8b471b9a! Will try again.
An error occurred while installing cryptography==2.9 --hash=sha256:19ae795137682a9778892fb4390c07811828b173741bce91e30f899424b3934d --hash=sha256:7598974f6879a338c785c513e7c5a4329fbc58b9f6b9a6305035fca5b1076552 --hash=sha256:6b744039b55988519cc183149cceb573189b3e46e16ccf6f8c46798bb767c9dc --hash=sha256:587f98ce27ac4547177a0c6fe0986b8736058daffe9160dcf5f1bd411b7fbaa1 --hash=sha256:0cacd3ef5c604b8e5f59bf2582c076c98a37fe206b31430d0cd08138aff0986e --hash=sha256:7a279f33a081d436e90e91d1a7c338553c04e464de1c9302311a5e7e4b746088 --hash=sha256:cc20316e3f5a6b582fc3b029d8dc03aabeb645acfcb7fc1d9848841a33265748 --hash=sha256:ed1d0760c7e46436ec90834d6f10477ff09475c692ed1695329d324b2c5cd547 --hash=sha256:1b9b535d6b55936a79dbe4990b64bb16048f48747c76c29713fea8c50eca2acf --hash=sha256:192ca04a36852a994ef21df13cca4d822adbbdc9d5009c0f96f1d2929e375d4f --hash=sha256:3be7a5722d5bfe69894d3f7bbed15547b17619f3a88a318aab2e37f457524164 --hash=sha256:5aca6f00b2f42546b9bdf11a69f248d1881212ce5b9e2618b04935b87f6f82a1 --hash=sha256:9fc9da390e98cb6975eadf251b6e5fa088820141061bf041cd5c72deba1dc526 --hash=sha256:2a2ad24d43398d89f92209289f15265107928f22a8d10385f70def7a698d6a02 --hash=sha256:95e1296e0157361fe2f5f0ed307fd31f94b0ca13372e3673fa95095a627636a1 --hash=sha256:ef9a55013676907df6c9d7dd943eb1770d014f68beaa7e73250fb43c759f4585 --hash=sha256:d1bf5a1a0d60c7f9a78e448adcb99aa101f3f9588b16708044638881be15d6bc --hash=sha256:6b91cab3841b4c7cb70e4db1697c69f036c8bc0a253edc0baa6783154f1301e4 --hash=sha256:49870684da168b90110bbaf86140d4681032c5e6a2461adc7afdd93be5634216! Will try again.
An error occurred while installing exifread==2.1.2 --hash=sha256:4aa9d227db5c4cd65d87520076140a6f84e33363e08e649b87c7afec6bab60ab --hash=sha256:79e244f2eb466709029e8806fe5e2cdd557870c3db5f68954db0ef548d9320ad! Will try again.
An error occurred while installing flask==1.1.1 --hash=sha256:13f9f196f330c7c2c5d7a5cf91af894110ca0215ac051b5844701f2bfd934d52 --hash=sha256:45eb5a6fd193d6cf7e0cf5d8a5b31f83d5faae0293695626f539a823e93b13f6! Will try again.
An error occurred while installing idna==2.9 --hash=sha256:a068a21ceac8a4d63dbfd964670474107f541babbd2250d61922f029858365fa --hash=sha256:7588d1c14ae4c77d74036e8c22ff447b26d0fde8f007354fd48a7814db15b7cb! Will try again.
An error occurred while installing inifile==0.4 --hash=sha256:891bc629f81477708581b30a7b0583bb5c9c2ee3c070afd4675ecd4f96b0d78d --hash=sha256:d712bdcee8a7b8894e0214a285d252202f99d5a3f592bd6793a776af8dce9907! Will try again.
An error occurred while installing itsdangerous==1.1.0 --hash=sha256:321b033d07f2a4136d3ec762eac9f16a10ccd60f53c0c91af90217ace7ba1f19 --hash=sha256:b12271b2047cb23eeb98c8b5622e2e5c5e9abd9784a153e9d8ef9cb4dd09d749! Will try again.
An error occurred while installing jinja2==2.11.1 --hash=sha256:b0eaf100007721b5c16c1fc1eecb87409464edc10469ddc9a22a27a99123be49 --hash=sha256:93187ffbc7808079673ef52771baa950426fd664d3aad1d0fa3e95644360e250! Will try again.
An error occurred while installing lektor==3.1.3 --hash=sha256:60568b3744b30d88dfb9daffefffe12fbbb5d1591a4ae4cff72ccc64a25c971a --hash=sha256:60a83e7a100780a58553324b396b0df32a2f584452184efbf87acefed85e564d! Will try again.
An error occurred while installing markupsafe==1.1.1 --hash=sha256:00bc623926325b26bb9605ae9eae8a215691f33cae5df11ca5424f06f2d1f473 --hash=sha256:535f6fc4d397c1563d08b88e485c3496cf5784e927af890fb3c3aac7f933ec66 --hash=sha256:98c7086708b163d425c67c7a91bad6e466bb99d797aa64f965e9d25c12111a5e --hash=sha256:29872e92839765e546828bb7754a68c418d927cd064fd4708fab9fe9c8bb116b --hash=sha256:e8313f01ba26fbbe36c7be1966a7b7424942f670f38e666995b88d012765b9be --hash=sha256:9bf40443012702a1d2070043cb6291650a0841ece432556f784f004937f0f32c --hash=sha256:09c4b7f37d6c648cb13f9230d847adf22f8171b1ccc4d5682398e77f40309235 --hash=sha256:24982cc2533820871eba85ba648cd53d8623687ff11cbb805be4ff7b4c971aff --hash=sha256:46c99d2de99945ec5cb54f23c8cd5689f6d7177305ebff350a58ce5f8de1669e --hash=sha256:717ba8fe3ae9cc0006d7c451f0bb265ee07739daf76355d06366154ee68d221e --hash=sha256:9add70b36c5666a2ed02b43b335fe19002ee5235efd4b8a89bfcf9005bebac0d --hash=sha256:c8716a48d94b06bb3b2524c2b77e055fb313aeb4ea620c8dd03a105574ba704f --hash=sha256:8defac2f2ccd6805ebf65f5eeb132adcf2ab57aa11fdf4c0dd5169a004710e7d --hash=sha256:43a55c2930bbc139570ac2452adf3d70cdbb3cfe5912c71cdce1c2c6bbd9c5d1 --hash=sha256:88e5fcfb52ee7b911e8bb6d6aa2fd21fbecc674eadd44118a9cc3863f938e735 --hash=sha256:ade5e387d2ad0d7ebf59146cc00c8044acbd863725f887353a10df825fc8ae21 --hash=sha256:6788b695d50a51edb699cb55e35487e430fa21f1ed838122d722e0ff0ac5ba15 --hash=sha256:09027a7803a62ca78792ad89403b1b7a73a01c8cb65909cd876f7fcebd79b161 --hash=sha256:500d4957e52ddc3351cabf489e79c91c17f6e0899158447047588650b5e69183 --hash=sha256:596510de112c685489095da617b5bcbbac7dd6384aeebeda4df6025d0256a81b --hash=sha256:62fe6c95e3ec8a7fad637b7f3d372c15ec1caa01ab47926cfdf7a75b40e0eac1 --hash=sha256:ba59edeaa2fc6114428f1637ffff42da1e311e29382d81b339c1817d37ec93c6 --hash=sha256:6dd73240d2af64df90aa7c4e7481e23825ea70af4b4922f8ede5b9e35f78a3b1 --hash=sha256:1027c282dad077d0bae18be6794e6b6b8c91d58ed8a8d89a89d59693b9131db5 --hash=sha256:79855e1c5b8da654cf486b830bd42c06e8780cea587384cf6545b7d9ac013a0b --hash=sha256:cd5df75523866410809ca100dc9681e301e3c27567cf498077e8551b6d20e42f --hash=sha256:7c1699dfe0cf8ff607dbdcc1e9b9af1755371f92a68f706051cc8c37d447c905 --hash=sha256:b00c1de48212e4cc9603895652c5c410df699856a2853135b3967591e4beebc2 --hash=sha256:cdb132fc825c38e1aeec2c8aa9338310d29d337bebbd7baa06889d09a60a1fa2 --hash=sha256:e249096428b3ae81b08327a63a485ad0878de3fb939049038579ac0ef61e17e7 --hash=sha256:b2051432115498d3562c084a49bba65d97cf251f5a331c64a12ee7e04dacc51b --hash=sha256:b1282f8c00509d99fef04d8ba936b156d419be841854fe901d8ae224c59f0be5 --hash=sha256:13d3144e1e340870b25e7b10b98d779608c02016d5184cfb9927a9f10c689f42! Will try again.
An error occurred while installing mistune==0.8.4 --hash=sha256:88a1051873018da288eee8538d476dffe1262495144b33ecb586c4ab266bb8d4 --hash=sha256:59a3429db53c50b5c6bcc8a07f8848cb00d7dc8bdb431a4ab41920d201d4756e! Will try again.
An error occurred while installing pathtools==0.1.2 --hash=sha256:7c35c5421a39bb82e58018febd90e3b6e5db34c5443aaaf742b3f33d4655f1c0! Will try again.
An error occurred while installing pycparser==2.20 --hash=sha256:2d475327684562c3a96cc71adf7dc8c4f0565175cf86b6d7a404ff4c771f15f0 --hash=sha256:7582ad22678f0fcd81102833f60ef8d0e57288b6b5fb00323d101be910e35705! Will try again.
An error occurred while installing pyopenssl==19.1.0 --hash=sha256:621880965a720b8ece2f1b2f54ea2071966ab00e2970ad2ce11d596102063504 --hash=sha256:9a24494b2602aaf402be5c9e30a0b82d4a5c67528fe8fb475e3f3bc00dd69507! Will try again.
An error occurred while installing pytz==2019.3 --hash=sha256:b02c06db6cf09c12dd25137e563b31700d3b80fcc4ad23abb7a315f2789819be --hash=sha256:1c557d7d0e871de1f5ccd5833f60fb2550652da6be2693c1e02300743d21500d! Will try again.
An error occurred while installing requests[security]==2.23.0 --hash=sha256:b3f43d496c6daba4493e7c431722aeb7dbc6288f52a6e04e7b6023b0247817e6 --hash=sha256:43999036bfa82904b6af1d99e4882b560e5e2c68e5c4b0aa03b655f3d7d73fee! Will try again.
An error occurred while installing six==1.14.0 --hash=sha256:8f3cd2e254d8f793e7f3d6d9df77b92252b52637291d0f0da013c76ea2724b6c --hash=sha256:236bdbdce46e6e6a3d61a337c0f8b763ca1e8717c03b369e87a7ec7ce1319c0a! Will try again.
An error occurred while installing urllib3==1.25.8 --hash=sha256:2f3db8b19923a873b3e5256dc9c2dedfa883e33d87c690d9c7913e1f40673cdc --hash=sha256:87716c2d2a7121198ebcb7ce7cccf6ce5e9ba539041cfbaeecfb641dc0bf6acc! Will try again.
An error occurred while installing watchdog==0.10.2 --hash=sha256:c560efb643faed5ef28784b2245cf8874f939569717a4a12826a173ac644456b! Will try again.
An error occurred while installing werkzeug==0.16.1 --hash=sha256:1e0dedc2acb1f46827daa2e399c1485c8fa17c0d8e70b6b875b4e7f54bf408d2 --hash=sha256:b353856d37dec59d6511359f97f6a4b2468442e454bd1c98298ddce53cac1f04! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 24/24 — 00:00:00
Installing initially failed dependencies…
[InstallError]:   File "/home/mayank/.local/lib/python3.8/site-packages/pipenv/cli/command.py", line 232, in install
[InstallError]:       retcode = do_install(
[InstallError]:   File "/home/mayank/.local/lib/python3.8/site-packages/pipenv/core.py", line 2051, in do_install
[InstallError]:       do_init(
[InstallError]:   File "/home/mayank/.local/lib/python3.8/site-packages/pipenv/core.py", line 1306, in do_init
[InstallError]:       do_install_dependencies(
[InstallError]:   File "/home/mayank/.local/lib/python3.8/site-packages/pipenv/core.py", line 900, in do_install_dependencies
[InstallError]:       batch_install(
[InstallError]:   File "/home/mayank/.local/lib/python3.8/site-packages/pipenv/core.py", line 796, in batch_install
[InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
[InstallError]:   File "/home/mayank/.local/lib/python3.8/site-packages/pipenv/core.py", line 703, in _cleanup_procs
[InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: Traceback (most recent call last):
[pipenv.exceptions.InstallError]:   File "/home/mayank/.local/share/virtualenvs/creativecommons.github.io-source-rH5OX07R/bin/pip", line 5, in <module>
[pipenv.exceptions.InstallError]:     from pip._internal.cli.main import main
[pipenv.exceptions.InstallError]:   File "/home/mayank/.local/share/virtualenvs/creativecommons.github.io-source-rH5OX07R/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 10, in <module>
[pipenv.exceptions.InstallError]:     from pip._internal.cli.autocompletion import autocomplete
[pipenv.exceptions.InstallError]:   File "/home/mayank/.local/share/virtualenvs/creativecommons.github.io-source-rH5OX07R/lib/python3.7/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
[pipenv.exceptions.InstallError]:     from pip._internal.cli.main_parser import create_main_parser
[pipenv.exceptions.InstallError]:   File "/home/mayank/.local/share/virtualenvs/creativecommons.github.io-source-rH5OX07R/lib/python3.7/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
[pipenv.exceptions.InstallError]:     from pip._internal.cli import cmdoptions
[pipenv.exceptions.InstallError]:   File "/home/mayank/.local/share/virtualenvs/creativecommons.github.io-source-rH5OX07R/lib/python3.7/site-packages/pip/_internal/cli/cmdoptions.py", line 19, in <module>
[pipenv.exceptions.InstallError]:     from distutils.util import strtobool
[pipenv.exceptions.InstallError]: ModuleNotFoundError: No module named 'distutils.util'
ERROR: Couldn't install package: babel
 Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 7/24 — 00:00:00
/usr/lib/python3.8/subprocess.py:942: ResourceWarning: subprocess 29263 is still running
  _warn("subprocess %s is still running" % self.pid,
sys:1: ResourceWarning: unclosed file <_io.FileIO name=8 mode='wb' closefd=True>
sys:1: ResourceWarning: unclosed file <_io.FileIO name=9 mode='rb' closefd=True>
/usr/lib/python3.8/subprocess.py:942: ResourceWarning: subprocess 29265 is still running
  _warn("subprocess %s is still running" % self.pid,
sys:1: ResourceWarning: unclosed file <_io.FileIO name=10 mode='wb' closefd=True>
sys:1: ResourceWarning: unclosed file <_io.FileIO name=11 mode='rb' closefd=True>
</detail>

I have tried running `pipenv --rm`and then `pipenv install` but this does not fix anything. Anyone knows how to fix this?

**Comment by Dhruvi16** [comment]
Hey! @makkoncept the plugin is already installed and on running the command `lektor plugin list` I get this -
![image](https://user-images.githubusercontent.com/34674462/84432225-27973600-ac4a-11ea-9cfa-c2d0c2eaf848.png)

And I could not reproduce the error you got. I tried running `pipenv --rm` and then `pipenv install` but still it was running fine.

**Comment by makkoncept** [comment]
You can try running the following commands anyway :
`lektor plugin flush-cache` and then  `lektor plugin reinstall`

**Comment by kgodey** [comment]
I can now reproduce the error on `master` for some reason, I didn't make any changes.

I haven't had time to look into it but hopefully tomorrow.

**Comment by kgodey** [comment]
> Running `lektor plugin flush-cache` and then `lektor plugin reinstall` fixed the build for me.

**Comment by Dhruvi16** [comment]
This makes the local build work fine for me but I am not sure how to handle the staging environment. As there are no code changes. 
@dhruvkb do you have any idea?

**Comment by dhruvkb** [comment]
Netlify doesn't allow us to run a one-off command on the build server. Also, we can't SSH into the build machine like Travis CI either. So I'll just change the Netlify build command to 
```
lektor plugin flush-cache && lektor plugin reinstall && lektor build --build-flag webpack --output-path ./build
```
for the time being.

**Comment by dhruvkb** [comment]
Thanks @makkoncept! The commands did indeed fix the builds locally and also on Netlify. I still have no idea what caused the builds to fail in the first place but it's nice to know that there's a handy solution.

**Comment by kgodey** [comment]
Nice work on this @Dhruvi16 @dhruvkb @makkoncept
