### ISSUE TITLE
Add Vocabulary as a featured project.

### ISSUE THREAD

**Issue by Dhruvi16** [creativecommons/creativecommons.github.io-source#331]
## Problem

According to new mockups, there are three featured projects on the home page. Here's the [link](https://www.figma.com/file/mttcugI1UxvCJRKE5sdpbO/Mockups?node-id=759%3A516). 

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by Dhruvi16** [comment]
Made changes in [PR-528](https://github.com/creativecommons/vocabulary/pull/528)

**Comment by kgodey** [comment]
Vocabulary is now a featured project: https://opensource.creativecommons.org/contributing-code/projects/
