### ISSUE TITLE
Documentation does not comprehensively cover setup steps

### ISSUE THREAD

**Issue by madewithkode** [creativecommons/creativecommons.github.io-source#374]
## Description
The project setup guide on the project documentation is not detailed enough and does not accurately reflect the actual project setup process step by step.  It leaves a couple necessary steps for the contributor to  figure, which is not so beginner-friendly.

## Resolution
- [ x] I would be interested in resolving this bug.

**Comment by makkoncept** [comment]
Hi @madewithkode Can you please elaborate more. What are the steps that need to be made more verbose?
