### ISSUE TITLE
Wrong hover style of a single link

### ISSUE THREAD

**Issue by panchovm** [creativecommons/creativecommons.github.io-source#391]
### Page: Home
The default and hover states of the link `visit website` have wrong styles. This also applies to Github and Slack links shown below.

## Expectation
In the default state, It should not have the left, top, and bottom padding. During hover, it should only have an underline style without changing the background color.

## Screenshots
<img width="332" alt="Screen Shot 2020-08-03 at 11 47 08" src="https://user-images.githubusercontent.com/895819/89201574-b3a94800-d57f-11ea-9793-d248daf95daf.png">

**Comment by Dhruvi16** [comment]
This issue is handled by https://github.com/creativecommons/vocabulary/issues/370. So I am closing this issue.
