### ISSUE TITLE
The navigation component doesn't behave as expected

### ISSUE THREAD

**Issue by panchovm** [creativecommons/creativecommons.github.io-source#396]
### Page: Single entry (Contribution Guidelines)
The navigation component (table of content) doesn't remain fixed during scrolling.

## Expectation
The component should remain fixed once user scrolls down or up.

## Screenshots
<img width="366" alt="Screen Shot 2020-08-03 at 15 01 56" src="https://user-images.githubusercontent.com/895819/89217660-8f0e9980-d59a-11ea-95f8-538d8821c905.png">

**Comment by Dhruvi16** [comment]
I am not sure how will it stay fixed. Are you saying that all the contents are present in 100% height and there is scroll for content only?

**Comment by panchovm** [comment]
I mean [something like this](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_sidenav_fixed2). Where only that section keeps fixed.

**Comment by Dhruvi16** [comment]
I don't think this will look good because in our case the side menu is placed in the middle of the page.
![simplescreenrecorder-2020-08-06_15 30 12](https://user-images.githubusercontent.com/34674462/89521243-c4b2bd00-d7fc-11ea-918c-6608a47c0cca.gif)

**Comment by zackkrida** [comment]
@Dhruvi16 have you used `position: sticky` before? It would let you keep it centered initially but would then fix it to the top once you scroll. 

I can give you some tips on using it if you haven't!

**Comment by panchovm** [comment]
Look [this case](https://www.airbnb.cl/experiences/414849?checkin=2020-10-12&checkout=2020-10-23&adults=1&children=0&infants=0&location=Roma%2C%20RM&currentTab=experience_tab&federatedSearchId=2f72857b-18fe-4dc5-b718-143c0afb99c6&searchId=&sectionId=931573d1-ac52-43f8-b73e-eb01d7817204&source=p2), the sidebar is sticky when reaching the top position of the screen. To then keep the scroll when full-width content appears.

**Comment by Dhruvi16** [comment]
Hey, @zackkrida I tried using sticky but it did not work. I am not very familiar with it so some help would be great!
Thanks.

**Comment by zackkrida** [comment]
Ah okay @Dhruvi16 I made a pr you can review here: https://github.com/creativecommons/creativecommons.github.io-source/pull/418

**Comment by panchovm** [comment]
@zackkrida and @Dhruvi16, does the example that I posted make sense?

**Comment by zackkrida** [comment]
@panchovm yes definitely. Please review the `.gif` here: https://github.com/creativecommons/creativecommons.github.io-source/pull/418

is that what you're expecting to see?

**Comment by panchovm** [comment]
Yes! <3 it looks great.
