### ISSUE TITLE
Top nav items are not very bright

### ISSUE THREAD

**Issue by kgodey** [creativecommons/creativecommons.github.io-source#4]
Maybe we could match the nav styling of creativecommons.org?
![screen shot 2019-02-05 at 2 53 53 pm](https://user-images.githubusercontent.com/287034/52300494-fa4fbf00-2955-11e9-9f03-26911d476889.png)

**Comment by hugosolar** [comment]
Fixed in https://github.com/creativecommons/creativecommons.github.io-source/commit/df4320f4562fc9d3fc56feffdc4fab668d333f99
- Underline active items
- Layout fix (header aligned to right)

**Comment by kgodey** [comment]
Could you make the minimum width of the header the same as the main container's width?

**Comment by kgodey** [comment]
@hugosolar could you also add "Creative Commons Open Source" to the header of the site since that's what we decided on?

**Comment by hugosolar** [comment]
Ok, done
- Fixed header align in https://github.com/creativecommons/creativecommons.github.io-source/commit/6ef03d5559a2970f611bdcec62c356ccbe0a9ce3
- Fixed footer align and style fixes also in https://github.com/creativecommons/creativecommons.github.io-source/commit/c3aa175c087a5f5e0e6d2de92c37994e6280e18d
- Text added down the main logo in the header in https://github.com/creativecommons/creativecommons.github.io-source/commit/c3aa175c087a5f5e0e6d2de92c37994e6280e18d
