### ISSUE TITLE
Back to top directs to the first heading and not the header.

### ISSUE THREAD

**Issue by sanjana11147** [creativecommons/creativecommons.github.io-source#40]
Description:
On clicking the back to top button, the user is directed to the first heading of the web page and not the footer, so if one has to choose another tab, they have to further scroll up manually.

Fix:
Change the back to top button to direct to the top of the web page and not the first heading.

**Comment by sanjana11147** [comment]
@kgodey @hugosolar Please review. I would like to work on it.

**Comment by kgodey** [comment]
Go ahead!
