### ISSUE TITLE
Incorrect style and behavior in steps section

### ISSUE THREAD

**Issue by panchovm** [creativecommons/creativecommons.github.io-source#400]
### Page: Guide (Building a New Feature in CC Search)
The section has the following errors:
1. The left section must have the `Lighter Gray` as background-color.
2. Once the user scrolls up or down, the section should remain fixed.
3. When the user is seeing a section on content section, the steps section must show the active step as its hover style.

## Screenshots
<img width="714" alt="Screen Shot 2020-08-03 at 15 57 50" src="https://user-images.githubusercontent.com/895819/89221991-39d68600-d5a2-11ea-968f-e22be6608edb.png">

**Comment by Dhruvi16** [comment]
The first part will be solved in Vocabulary itself - https://github.com/creativecommons/vocabulary/issues/579
