### ISSUE TITLE
The last row of posts in post table should not have the divider line

### ISSUE THREAD

**Issue by panchovm** [creativecommons/creativecommons.github.io-source#404]
### Page: Blog
In the post table, the last row of posts should not have the bottom line to divide the content and pagination component

## Screenshot
<img width="1389" alt="Screen Shot 2020-08-03 at 17 12 48" src="https://user-images.githubusercontent.com/895819/89227973-abb3cd00-d5ac-11ea-9057-7797fcdc902e.png">

**Comment by Dhruvi16** [comment]
I am not sure how to do this. I have given border to the card here and I am not sure how to selectively remove the border from (1,2 or 3) cards in the last row.

**Comment by zackkrida** [comment]
@Dhruvi16 it's a little hacky, but something like this with the [`:nth-last-child()` pseudoselector](https://www.w3schools.com/cssref/sel_nth-last-child.asp) is probably the best way! That will let you target the 2nd to last and 3rd to last elements, and you can get the last element with the `:last-child` selector.

**Comment by Dhruvi16** [comment]
I tried that but the last row can have 1,2 or 3 cards how do I know how many cards to select.

**Comment by Dhruvi16** [comment]
I found a solution and made the PR.
