### ISSUE TITLE
Make images not selectable and not draggable

### ISSUE THREAD

**Issue by TrustedMercury** [creativecommons/creativecommons.github.io-source#411]
##  Description
Make images on the website not selectable or draggable. All images on the website can be dragged and selected which is against convention.
[![Example Image](https://i.ibb.co/FsbdbLN/draggable-Image.png)]()

## Implementation
- [x] I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
@TrustedMercury I disagree with your conventions on this topic.

I believe allowing images to be dragged is acceptable. I frequently use drag-and-drop to save images from the browser to my device.
<img width="1440" alt="Screenshot 2020-08-05 at 3 25 33 PM" src="https://user-images.githubusercontent.com/16580576/89399340-f447c380-d72f-11ea-9724-3fd0561ba414.png">

The same goes for being able to select images as you can then copy and paste into a rich text editor to get not only the text but also the images on the page. I'm not sure this is an issue that we need to solve but I'll still keep it open in case someone aligns with your observations.

**Comment by kgodey** [comment]
I concur with @dhruvkb, we do not need to fix this. We hope to see other contributions from you, @TrustedMercury! :)
