### ISSUE TITLE
HTML errors 

### ISSUE THREAD

**Issue by TrustedMercury** [creativecommons/creativecommons.github.io-source#412]
## Description

The website has a few HTML errors -
- `<nav>` elements do not have a `name` attribute but one is provided on ``Line 52 https://opensource.creativecommons.org/``
- `<nav>` element closes but `<div>` element in it is still open on ``Line 71 - Line 72 https://opensource.creativecommons.org/``
- `align` attribute is no longer supported for `div` elements in `HTML5`, must use `CSS` instead. ``Line 96, 102, etc. https://opensource.creativecommons.org/``

## Reproduction

Bug is not visible on the page, but affects the code.

## Expectation
Since the bug is not visible on the page, it still displays what it should but the code isn't right

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
@TrustedMercury the lines numbers that you mentioned in the issue, are they the line numbers in the final HTML source code of the page?

**Comment by TrustedMercury** [comment]
I referred this - view-source:https://opensource.creativecommons.org/ to get the line numbers, let me make a new copy as it seems some of them are slightly inaccurate.
- `<nav>` elements do not have a name attribute but one is provided on `Line 52 https://opensource.creativecommons.org/`
- `<nav>` element closes but `<div>` element in it is still open on `Line 143 - Line 144 https://opensource.creativecommons.org/`
- The `align` attribute is no longer supported for div elements in `HTML5`, must use `CSS` instead. `Line 164, 173, 183, 193, etc. https://opensource.creativecommons.org/`

**Comment by dhruvkb** [comment]
Hi, @TrustedMercury the contents of `view-source` are dynamically generated using Lektor and, since you expressed an interest in solving this issue, I would recommend setting the project up locally. You can take some time to identify the location in the source code from where these particular DOM elements are being generated.

**Comment by TrustedMercury** [comment]
I forked it and set it up locally, will work on it now!
