### ISSUE TITLE
Styling issue on mobile

### ISSUE THREAD

**Issue by code-n-chill** [creativecommons/creativecommons.github.io-source#42]
**Describe the bug**
The text on some pages is not properly aligned when seen from mobile.

**To Reproduce**
1. Go to 'community' tab on navbar
2. Click on 'any link' from dropdown
3. See the styling issue with 'jump to' list.

**Expected behavior**
Should be properly aligned with rest of page.

**Screenshots**
![Screenshot_20190320_041926](https://user-images.githubusercontent.com/21370078/54647205-ad6c1600-4ac7-11e9-9971-f92860a37e99.jpg)

**Smartphone (please complete the following information):**
 - Device: Vivo V9
 - OS: Android 6
 - Browser : Chrome

**Comment by sanjana11147** [comment]
I would like to work on this issue @kgodey @code-n-chill

**Comment by code-n-chill** [comment]
@sanjana11147, since you made a chnge in css file of the project whicg after my changes no longer exist. You can create a new PR with similar change in width of toc card of sass file located in webpack directory of the repo.
