### ISSUE TITLE
Syntax highlighting code snippets for blog posts

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/creativecommons.github.io-source#434]
## Problem
Code blocks don't have any styling, which makes them difficult to read. We should set up syntax highlighting.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by krysal** [comment]
That is already implemented in #226. The problem may be with a specific blog post, since it is necessary to specify the language of the snippet.

**Comment by aldenstpage** [comment]
Ah, that's what I was missing. Thank you @krysal!
