### ISSUE TITLE
[new design] Not enough spacing between filters and project ideas

### ISSUE THREAD

**Issue by kgodey** [creativecommons/creativecommons.github.io-source#442]
See screenshot (this is on the Project Ideas page)

<img width="1297" alt="Screen Shot 2020-08-17 at 10 57 00 AM" src="https://user-images.githubusercontent.com/287034/90410541-7d3bf480-e078-11ea-9146-d61c24788db6.png">

**Comment by Dhruvi16** [comment]
This was fixed by - https://github.com/creativecommons/creativecommons.github.io-source/pull/420 . Wow I do not know how did it change into this. Lemme see.

**Comment by kgodey** [comment]
Looks fixed.
