### ISSUE TITLE
[new design] Issues with Project List page

### ISSUE THREAD

**Issue by kgodey** [creativecommons/creativecommons.github.io-source#443]
Two issues:
- It is not clear that the items in the last column (Website, GitHub, Slack, etc.) are clickable, they have the same styling as the description etc. which is not clickable
- There is no icon for "Website", it should use the external link icon.

Maybe we can use the same buttons we use for the cards?

<img width="1281" alt="Screen Shot 2020-08-17 at 11 04 14 AM" src="https://user-images.githubusercontent.com/287034/90411253-7a8dcf00-e079-11ea-9731-6b9d4d173418.png">

**Comment by Dhruvi16** [comment]
I will add the external link icon to the website link. But I wanted to ask @panchovm that if we can make them forest green so they appear as links.

**Comment by panchovm** [comment]
Using forest green to indicate that are links sounds good.

**Comment by kgodey** [comment]
Looks good!
