### ISSUE TITLE
[new Design] Date on the Blog post page is not zero padded

### ISSUE THREAD

**Issue by Aakash2408** [creativecommons/creativecommons.github.io-source#468]
Hey @kgodey  @TimidRobot 
## Description
When we check the blog page date shown is not zero padded for single digit dates.I have corrected this issue in the old version website .

## Expectation
  Format should be {yyyy-mm-dd}

## Screenshots
![Screenshot from 2020-08-21 03-11-07](https://user-images.githubusercontent.com/47134609/90848420-62a99a00-e35c-11ea-8fc5-24ebe786dbd0.png)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
As #440 mentions that it affects both old and new designs, it has been reopened and this issue, being a duplicate, of the same issue is being closed. @Aakash2408 you remain assigned to it so please take it up!

**Comment by Aakash2408** [comment]
But i made changes in blog post which is the code for old site  and that
made the changes too but where can i make changes for this new website
