### ISSUE TITLE
Ordering of Roles under some projects

### ISSUE THREAD

**Issue by akshgpt7** [creativecommons/creativecommons.github.io-source#481]
## Description
On the [Community Team page](https://opensource.creativecommons.org/community/community-team/members/), the ordering of the roles under **CC Catalog API** and **Community Building Teams** seems to be in reverse order than all others (This is only the case with these two categories).
It looks a little inconsistent with the other Projects ordered differently.

## Reproduction

Visit the  [Community Team page](https://opensource.creativecommons.org/community/community-team/members/).

## Expectation

The order should be reversed to have decreasing priority of roles.

## Screenshots

![Screenshot from 2020-08-26 06-35-14](https://user-images.githubusercontent.com/20405311/91244034-f7e7cc80-e768-11ea-9292-5921d5989b4f.png)

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by kgodey** [comment]
Thanks for reporting this @akshgpt7!

**Comment by ooyeraju** [comment]
Can I take this?

**Comment by kgodey** [comment]
Sure, go ahead @ooyeraju. No need to ask in advance if an issue is marked "help wanted".

**Comment by kgodey** [comment]
Fixed in https://github.com/creativecommons/ccos-scripts/issues/70
