### ISSUE TITLE
Update donate icon in footer button

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/creativecommons.github.io-source#484]
The icon in the footer donate button needs to be updated to use the `cc-letterheart-filled` icon.

Original Issue: creativecommons/vocabulary#589

**Comment by abhinav72610** [comment]
can i do this ??

**Comment by kgodey** [comment]
go ahead @abhinav72610. You don't need to ask permission if something is marked "help wanted".

You may want to look at a similar PR in the CC Search repo: https://github.com/creativecommons/cccatalog-frontend/pull/1192
