### ISSUE TITLE
Header responsiveness

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/creativecommons.github.io-source#498]
The header of http://opensource.creativecommons.org/ has some overlap issues. We should fix this by moving `Archive` to the blue links in site footer and removing `Contribution Guidelines` from those links.

The new footer `Archive` link should link to an "Archive page", which has two links on it:

- [CC Tech Blog (2007-2014)](https://opensource.creativecommons.org/archives/old-tech-blog)
- [CC-DEVEL Mailing List (2005-2015)](https://lists.ibiblio.org/pipermail/cc-devel/)

## Supplemental Details

We are having continued issues with the responsiveness of the header. The adjustments to spacing and font size made an improvement, but ultimately we need to remove a menu item. I propose we remove the `archive` items from the menu.

<img width="1375" alt="Screen Shot 2020-08-31 at 8 59 16 AM" src="https://user-images.githubusercontent.com/6351754/91757687-7332ef00-eb6a-11ea-965a-071a0fc93a09.png">

<img width="1155" alt="Screen Shot 2020-08-31 at 8 59 21 AM" src="https://user-images.githubusercontent.com/6351754/91757672-6dd5a480-eb6a-11ea-8a72-579f264e4aa4.png">
</div>

Long term though, this site has quite a few pages. I would also suggest we find a better way to showcase these. One suggestion would be a sub-footer with categorized menu items:

<img width="782" alt="Screen Shot 2020-08-31 at 9 17 44 AM" src="https://user-images.githubusercontent.com/6351754/91757957-e5a3cf00-eb6a-11ea-8a3b-d0e5e86f5094.png">

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
@zackkrida I'm getting errors on the screenshots you've attached. 
<img width="906" alt="Screenshot 2020-09-02 at 10 03 20 AM" src="https://user-images.githubusercontent.com/16580576/91932357-89c07e00-ed03-11ea-8a81-eedf328ab204.png">

**Comment by kgodey** [comment]
I don't mind moving Archive to the footer, but what about the sub-items? I guess we could make an "Archive" page that links to the sub-items.

**Comment by Zeeshan-2k1** [comment]
Can I take this. I want to work on this.

**Comment by zackkrida** [comment]
I like the Archive page idea, until we have some more robust sub-menu/sitemap menu type section in the footer globally.

**Comment by kgodey** [comment]
@zackkrida will you update the ticket description?

**Comment by Aakash2408** [comment]
Can i take this?

**Comment by zackkrida** [comment]
@Aakash2408 you are welcome to work on this; I updated the ticket with specific instructions.
