### ISSUE TITLE
Split Sass into smaller files

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/creativecommons.github.io-source#501]
Currently all styling from the site comes from a single Sass file `main.scss` in `webpack/sass`. This causes:
- a maintenance burden (at the time of writing, the file contains > 700 lines)
- longer loading times (the single `.css` output for the entire site is loaded on the first page visit)

Since Webpack is being used, a better way would be to split the file into smaller chunks and use a number of different entrypoints to facilitate code splitter for a more manageable experience for developers and faster loading experience for end users.

**Comment by Zeeshan-2k1** [comment]
I am new to this community. I want to work on this.

**Comment by dhruvkb** [comment]
@Dhruvi16 can you help @Zeeshan-2k1 with this?

**Comment by Dhruvi16** [comment]
Yes! Of course.

**Comment by Dhruvi16** [comment]
We will have to split the CSS based on the templates they are related to. I have added comments in the main.scss and those will help you find the templates each piece of code is related to.

**Comment by Zeeshan-2k1** [comment]
Sure, I am working on it.
