### ISSUE TITLE
Use new colored label component in `/contributing-code` page

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/creativecommons.github.io-source#507]
## Problem

Once #502 lands, we should use the new `.gh-label` css classes on [this page](https://github.com/creativecommons/creativecommons.github.io-source/blob/master/content/contributing-code/contents.lr), instead of inline code blocks.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
To whoever works on this, you can use the [Repository Labels](https://opensource.creativecommons.org/contributing-code/repo-labels/) page as a reference.

**Comment by ooyeraju** [comment]
I can take this.
