### ISSUE TITLE
Document JavaScript coding guidelines

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/creativecommons.github.io-source#509]
## Issue Description

I intend to write guidelines and base configuration files for working with JavaScript in Creative Commons projects. This will include:

- Best practices
- Prettier configuration
- Eslint configuration
- JSON formatting
- Vue standards

This will most likely live on the open source site, and perhaps the wiki. We don't have _existing language guides_ so this would possibly be the first and set some precedents for other guides. In that aim I'd like to follow some certain language conventions:

- Avoiding language like "simply|just|easy" see: https://jameshfisher.com/2017/02/22/dont-use-simply/
- Consider items in the Mozilla Writing Style Guide: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Writing_style_guide
- Take guidance in structure from Firefox JS Guidelines: https://firefox-source-docs.mozilla.org/code-quality/coding-style/coding_style_js.html

**Comment by dhruvkb** [comment]
Also include the following files:
- `.editorconfig`
- `.browserslistrc` (unsure about this, though it would be good to atleast have a baseline agreement on what browsers we should support)

Some good/popular style guides to pick/inherit from:
- [Standard](https://standardjs.com/index.html)
- [Google](https://google.github.io/styleguide/jsguide.html)
- [Airbnb](https://github.com/airbnb/javascript)

**Comment by Cronus1007** [comment]
@zackkrida @dhruvkb Also when we commit our changes we should implement things like `husky hooks` with `pre-commit`,`pre-push`, `post-ceckout`,`post-merge`.

**Comment by dhruvkb** [comment]
We do have a pre-commit hook to run `npm lint`. Not sure if we have any significant use for the rest.

**Comment by Cronus1007** [comment]
@dhruvkb But I don't see any while commiting. Just a suggestion to enhance developer exp.

**Comment by dhruvkb** [comment]
The pre-commit hook I talked about is setup in [Vocabulary](https://github.com/creativecommons/vocabulary), not all repos. I believe you have been working on this repo which does not have such hooks.

**Comment by Cronus1007** [comment]
@dhruvkb Yup I am working on this repo only. 
It would be a better approach to implement it on all the repos and we can  also build .sh scripts for checking preinstall ,install the dependencies and postinstal

**Comment by Cronus1007** [comment]
@dhruvkb Shall I implement all these functionlities.

**Comment by dhruvkb** [comment]
@Cronus1007 I think we should split the issue into bits and start with the styleguide. We can implement other features gradually so that the PRs are atomic and easier to review/merge.

**Comment by Cronus1007** [comment]
@zackkrida  @dhruvkb I think first I will initialise this repo with npm init for prettierconfigs. Since while commiting we will call a .sh script to format the document with prettier and will also lay out the structure of config of prettier
