### ISSUE TITLE
Blog: Show post categories in UI

### ISSUE THREAD

**Issue by kgodey** [creativecommons/creativecommons.github.io-source#51]
See **https://github.com/creativecommons/creativecommons.github.io-source/pull/43** for context. This should be worked on after https://github.com/creativecommons/creativecommons.github.io-source/pull/49 since that PR adds categories.

Post categories are currently not being displayed in the UI, they should be displayed on the post page. The design is up to you.

**Comment by makkoncept** [comment]
hi @kgodey, I would like to work on this. Can you assign it to me?

**Comment by kgodey** [comment]
Go ahead!
