### ISSUE TITLE
The repository does not generate a CC metadata file

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/creativecommons.github.io-source#516]
## Description
Each repo in the CC organisation should have a `.cc-metadata.yml` file. The OS@CC site repo generated from this one does not.

## Expectation
The `.cc-metadata.yml` file should be present.

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by kgodey** [comment]
It does, it's here: https://github.com/creativecommons/creativecommons.github.io-source/blob/master/.cc-metadata.yml

**Comment by snehal199** [comment]
Hey @dhruvkb, can I work on this?

**Comment by snehal199** [comment]
@dhruvkb could you give me some input as to what changes do I need to make exactly? It looks like there already is a .cc-metadata.yml file. Somewhat confused right now.

**Comment by dhruvkb** [comment]
So @snehal199, each repository should have a `.cc-metadata.yml` file. _This repo has one already_. 

But this repo is the source code for the actual OS@CC website which is in the repository [`creativecommons/creativecommons.github.io`](https://github.com/creativecommons/creativecommons.github.io). _That repo does not have one._ 

So the [build process](https://github.com/creativecommons/creativecommons.github.io-source/blob/master/.github/workflows/lektor-build-deploy.yml) for the site needs to be changed in such a way that the `.cc-metadata.yml` site from this repo is copied over to the compiled site when building.

**Comment by snehal199** [comment]
@dhruvkb, thank you for the feedback! I still didn't really understand what would be the way to resolve this issue. I looked up github actions since I don't really know how they work and found out some actions that copy files like [scp-action](https://github.com/appleboy/scp-action) and [copy via ssh](https://github.com/marketplace/actions/copy-via-ssh) but I am not quite sure if any of these solve the problem.

**Comment by dhruvkb** [comment]
@snehal199 let's take this from the top. Lektor has a build process that compiles the source code from this repo to a proper website that is in the `creativecommons.github.io` repo. This build process is: https://github.com/creativecommons/creativecommons.github.io-source/blob/6ff9518c0526f494a77a0ca6ebb3d8e307dc9639/.github/workflows/lektor-build-deploy.yml#L16

During this build process, Lektor copies everything in the [`assets/` directory](https://github.com/creativecommons/creativecommons.github.io-source/tree/master/assets) to the root of the built site. So the files you see in the assets directory are also present in the root of the `creativecommons.github.io` repo, eg: `LICENSE` and `README.md`. The one file that is the exception is `.cc-metadata.yml` _which has not been copied_.

Why just this file? See this [documentation page](https://www.getlektor.com/docs/project/file/). Here scroll to `Config Sections` > `[project]` > `excluded_assets`. The text there says that files starting with `.` are not copied over to the built files. Since the file `.cc-metadata.yml` starts with a `.`, it is not being copied over, which is what we want. 

So we must add `.cc-metadata.yml` to the `included_assets` key in the configuration:
https://github.com/creativecommons/creativecommons.github.io-source/blob/6ff9518c0526f494a77a0ca6ebb3d8e307dc9639/.lektorproject#L5

That should ensure that it is also copied over from `assets/` to `build/` during the build step. Hope this helps!

**Comment by snehal199** [comment]
Thank you @dhruvkb for the detailed explanation ! I definitely made things much more clear :smiley:. Will open a pr soon.
