### ISSUE TITLE
Use ISO-8601 date format on the issue finder

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/creativecommons.github.io-source#517]
## Description
Currently the issue finder formats dates as per the clients' locales.

https://github.com/creativecommons/creativecommons.github.io-source/blob/bd8fc4db7f2035e1009bc5502bd3b120ea8e6ce2/webpack/js/components.js#L72

This localisation is not immediately apparent and can cause confusion. Switching to the [ISO-8601 format](https://en.wikipedia.org/wiki/ISO_8601) for the dates should eliminate said confusion.

## Reproduction

1. Visit the [Issue Finder](https://opensource.creativecommons.org/contributing-code/issue-finder/).
2. See the non-standard dates.

## Expectation
The date should follow the ISO standard.

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by ooyeraju** [comment]
Hey, Can I take this?

**Comment by dhruvkb** [comment]
Sure @ooyeraju, please do.
