### ISSUE TITLE
Reduce commits by bot on the master branch 

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/creativecommons.github.io-source#523]
## Description
The Creative Commons bot makes a very large number of commits to the `master` branch to keep issues synchronised between GitHub organisation and the issues databag in the repository. This should be reduced as it quickly leads to forks and clones going out of date. Every other copy of the repository goes stale almost every hour.

## Reproduction

1. Fork the repository and wait for a couple of hours.
2. Your repository is now several commits behind `creativecommons:master`.

## Expectation
The commits should either be infrequent, or atomically small, or on a different branch. One of the simplest ways to do that is to eliminate the `updatedAt` field from the data, as even changes to that field (which happen very frequently) lead to new commits. A more long term approach would be to setup serverless functions on Netlify/Vercel to proxy authenticated requests to GitHub on behalf of the client as in [this example](https://github.com/dhruvkb/portfolio-api/blob/master/api/blog_posts/list.js).

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by akmadian** [comment]
Is this issue ready for work? If so, I can take it on. 

Will a naive solution work for now until we can get the plan for the more long term approach solidified?

**Comment by dhruvkb** [comment]
I think yes, this is a very pressing issue. Please just make sure we're not using the `updatedAt` value anywhere before we get rid of it.

**Comment by akmadian** [comment]
Okie dokie, I can do this in the next couple days.
