### ISSUE TITLE
Update the labels in Contribution Guidelines

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/creativecommons.github.io-source#533]
## Description
The section 'Proposing a new issue' still refers to the `not ready for work` label. This is old information. The new label that is applied to all new issues is `🚦 status: awaiting triage`.

## Expectation
The guidelines should contain accurate and up to date information.

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
For reference, see #526.

**Comment by Yashs911** [comment]
Hi, @dhruvkb I would like to work on this issue.

**Comment by dhruvkb** [comment]
@Yashs911 it's actually reserved for a demonstration, please pick a different issue.

**Comment by anandikb** [comment]
I'm interested to work on this issue.

**Comment by dhruvkb** [comment]
@Yashs911 you're free to work on this now, _if you still want to_.

**Comment by Yashs911** [comment]
@dhruvkb I guess someone else created a PR and it's already merged.

**Comment by dhruvkb** [comment]
No it was not merged to `master`, just to a dummy branch that was later deleted.
