### ISSUE TITLE
Blog: Create category pages that show posts associated with a category.

### ISSUE THREAD

**Issue by kgodey** [creativecommons/creativecommons.github.io-source#54]
We (will once https://github.com/creativecommons/creativecommons.github.io-source/issues/51 is done) show categories belonging blog posts but there's no way to see all posts in a given category. We should implement that feature and make each category associated with a blog post clickable to see all posts in that category.

**Comment by Anubhavshakya** [comment]
I would like to work on this...

**Comment by kgodey** [comment]
You'll need to wait until https://github.com/creativecommons/creativecommons.github.io-source/issues/51 is done to avoid conflicts since that changes categories as well. If you want to work on something now, I suggest https://github.com/creativecommons/creativecommons.github.io-source/issues/53 – it's similar but will not have conflicts with existing work.

**Comment by kgodey** [comment]
I'm removing the labels that indicate it's ready for work until #51 is done.

**Comment by kgodey** [comment]
Adding labels back since #51 is merged.

**Comment by makkoncept** [comment]
@kgodey can I work on this issue if no one is working on it.
Thanks

**Comment by kgodey** [comment]
Go ahead

**Comment by kgodey** [comment]
@makkoncept I made some changes to the URLs and categories in https://github.com/creativecommons/creativecommons.github.io-source/pull/61, please merge that into your branch early to avoid merge conflicts.

**Comment by makkoncept** [comment]
okay, will do :+1:

**Comment by makkoncept** [comment]
@kgodey I noticed  #62 _(generating author pages for multiple blogs)_ . I think we should also do this for categories so that structure of the blog can be consistent.
If you think so, shall I do this in this PR itself as I have not commited the changes yet or opening a new issue would be a good idea?

**Comment by kgodey** [comment]
Please do it in this PR, thanks!

**Comment by kgodey** [comment]
@makkoncept FYI, I updated some styles/text and fixed author pages which broke, see: https://github.com/creativecommons/creativecommons.github.io-source/compare/1304f579343f71d9c3e790a48c9a9b1c9fc3f2a8...a63295440d20024db0f80035f2397c8ed4ebec1c

Internal links also broke, I fixed in: https://github.com/creativecommons/creativecommons.github.io-source/commit/704788fed5288d41d0176086bc7888cf493d4b01

(I should have caught these during code review, sorry).

**Comment by makkoncept** [comment]
@kgodey I am sorry, I should have checked it. I will be more careful now.
