### ISSUE TITLE
Implement generated Open Graph Images 

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/creativecommons.github.io-source#553]
CC's Open Graph Image Generator has had enough styling improvements that it's ready for production!

https://cc-og-image.vercel.app/

We can use this to add custom OG images to all pages and blog posts. Here's an example tag and image for a standard page:

![og-image (1)](https://user-images.githubusercontent.com/6351754/98293992-4b3d7e80-1f53-11eb-8126-28ea30bf4898.png)

```html
<meta property="og:image" content="https://cc-og-image.vercel.app/This%20is%20the%20page%20title.png?theme=light&md=1&fontFamily=roboto-condensed&fontSize=100px&images=https%3A%2F%2Fcc-vocabulary.netlify.app%2Flogos%2Fproducts%2Fopen_source.svg%23opensource" />
```

The `This%20is%20the%20page%20title` piece should be replaced dynamically with the page's actual title.

## Blog Posts

For blog posts, we can include the author's image! Here's an example:

![og-image (2)](https://user-images.githubusercontent.com/6351754/98294388-f9492880-1f53-11eb-87b6-53d96b23e293.png)

```html
<meta property="og:image" content="https://cc-og-image.vercel.app/CREATIVE%20COMMONS%20WORDPRESS%20PLUGIN%3A%20ATTRIBUTION%20FOR%20IMAGES.png?theme=light&md=1&fontFamily=roboto-condensed&fontSize=100px&images=https%3A%2F%2Fcc-vocabulary.netlify.app%2Flogos%2Fproducts%2Fopen_source.svg%23opensource&images=https%3A%2F%2Fsecure.gravatar.com%2Favatar%2Fbca19ddd1522cb12edde0520d3d77ded%3Fsize%3D200%26d%3Dmp" />
```

The key for showing the author here is adding a second `&images={gravatar_url}` property to the meta url. In this case, that url is: `https%3A%2F%2Fsecure.gravatar.com%2Favatar%2Fbca19ddd1522cb12edde0520d3d77ded%3Fsize%3D200%26d%3Dmp`.

This will significantly improve the quality of social shares from the Open Source site.

**Comment by Cronus1007** [comment]
@zackkrida  #554 is going to close this issue or some additional PR'swould also be involved

**Comment by dhruvkb** [comment]
@Cronus1007 there is still scope for improvement after #554 is merged (as I've pointed out in https://github.com/creativecommons/creativecommons.github.io-source/pull/554#pullrequestreview-540409523). You could look into that if you'd like.
