### ISSUE TITLE
Code cleanup in 'Page with ToC' template

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/creativecommons.github.io-source#568]
## Description
The code in the 'Page with ToC' template ([`page-with-toc.html`](https://github.com/creativecommons/creativecommons.github.io-source/blob/master/themes/vocabulary_theme/templates/page-with-toc.html)) template writes a lot of repeated duplicate markup. This can be simplified using the features of Jinja templates such as [`for` loops](https://jinja.palletsprojects.com/en/2.11.x/templates/#for).

For reference see the [`layout.html`](https://github.com/creativecommons/creativecommons.github.io-source/blob/master/themes/vocabulary_theme/templates/layout.html) file which uses arrays and for loops in the header menu.

## Expectation
The code can be drastically improved to make use for less explicit markup and more logic-based generation.

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by Yashs911** [comment]
@dhruvkb  I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
Sure, @Yashs911. Please submit a PR when you're ready.

**Comment by prsndp** [comment]
I want to contribute to this project, Can you assign me this task??

**Comment by nimishbongale** [comment]
> I want to contribute to this project, Can you assign me this task??

@prsndp This issue already has a PR(#570) linked with it and some significant work has been done on it already. You can however, head over to the PR and give your inputs!

**Comment by prsndp** [comment]
Okay, thanks 👍🏻
