### ISSUE TITLE
Please remove me from the Code of Conduct committee

### ISSUE THREAD

**Issue by kgodey** [creativecommons/creativecommons.github.io-source#583]
See "Current Code of Conduct Committee" here: https://opensource.creativecommons.org/community/code-of-conduct/enforcement/

**Comment by Cronus1007** [comment]
@kgodey Let me send a PR fixing this issue. As well please provide me the updated list of the CODE OF CONDUCT COMMITTEE

**Comment by dhruvkb** [comment]
@Cronus1007 I believe the only change needed here is removing @kgodey's name from the list.

**Comment by kgodey** [comment]
Actually, the committee needs to be three people (per that page) so CC will need to figure out who will take my place. I marked the issue as "staff only" since CC staff needs to decide who that will be. CC is on winter break until Jan 4 so I don't expect this to get resolved before then.
