### ISSUE TITLE
Support generating authors pages for multiple blogs

### ISSUE THREAD

**Issue by kgodey** [creativecommons/creativecommons.github.io-source#62]
Currently, the authors page shows all authors associated with all blogs. Each blog should have its own authors list – the blog model was designed to support independent blogs so that we could also reuse it for a current CC tech blog. As part of this, we should also not hardcode the blog title in the author templates.

**Comment by makkoncept** [comment]
@kgodey Can I work on this issue?

**Comment by kgodey** [comment]
sure

**Comment by kgodey** [comment]
You might find these commits useful: https://github.com/creativecommons/creativecommons.github.io-source/compare/704788fed5288d41d0176086bc7888cf493d4b01...7fea06684de5539a3a1c20835cbecff3e052459d for removing the duplication of the blog name.

**Comment by makkoncept** [comment]
Cool! Thanks for this.

**Comment by makkoncept** [comment]
@kgodey  I think we should change
```
{% block title %}{{ this.parent.title }} - {{ this.name }}{% endblock %}
{% block header %}{{ this.parent.title }}{% endblock %}
```
in `blog-category.html` template to 
```
{% block title %}{{ this.parent.parent.children.get('entries').title + ' - ' + this.name }}{% endblock %}
{% block header %}{{ this.parent.parent.children.get('entries').title }}{% endblock %}
```
Title field was removed from `blog-categories.ini` model in 27badd06cbb3ae7c6c8635aabdea26f0703eef65

**Comment by kgodey** [comment]
@makkoncept that looks good, thanks.

**Comment by kgodey** [comment]
@makkoncept I made the change in https://github.com/creativecommons/creativecommons.github.io-source/commit/2edf7a9da84b32f89ea91b82546cb975988ae6ce.
