### ISSUE TITLE
Add more information regarding proposal selection, and mentor availability to GSoC "General Information" page.

### ISSUE THREAD

**Issue by akmadian** [creativecommons/creativecommons.github.io-source#63]
**Is your feature request related to a problem? Please describe.**
Recently in the cc-gsoc Slack channel, @kgodey provided some very useful information regarding mentor availability, and how `n` project ideas may be available, but there may only be enough mentors/ slots to support `< n` proposals. Additionally, she provided some information about proposal review criteria. She already added some of this information in #60, but I don't believe that what was added covers *all* of what could be useful to future participants.

**Describe the solution you'd like**
I believe that more available information is (in most cases) better, and I would have liked to have had this information when I started with GSoC. Because I believe that the addition of this information could help future GSoC participants, I would like to add more information regarding mentor/ slot availability to the `Mentors` section, and more information about the proposal review criteria to the `Proposal review criteria` section.

I would be happy to work with any maintainers to refine the language of the additions to be site-ready. Pending confirmation that this change is welcome, I will fork, and get to work!

**Describe alternatives you've considered**
I do not think there are any alternatives to just adding the information.

**Additional context**
Kriti's addition of proposal review criteria (PR #60)

These changes will be in [./content/gsoc-2019/contents.lr](https://github.com/creativecommons/creativecommons.github.io-source/blob/master/content/gsoc-2019/contents.lr)

Two recent threads in the cc-gsoc Slack channel: [Thread 1](https://creativecommons.slack.com/archives/CFXMFU4F6/p1554257285080700) (started by Theo M.; "Does Google ultimately decide what proposals are accepted or is it entirely the organization's choice?"), 
and [Thread 2](https://creativecommons.slack.com/archives/CFXMFU4F6/p1554271502090600) (started by myself; a continutation of the replies in thread 1).

**Comment by kgodey** [comment]
@akmadian do you want to work on this?

**Comment by akmadian** [comment]
Sure!
