### ISSUE TITLE
[Change] Add `#cc-dev-searchportal` slack channel information to site

### ISSUE THREAD

**Issue by possumbilities** [creativecommons/creativecommons.github.io-source#680]
## Problem
The [Join The CC Developer Community](https://opensource.creativecommons.org/community/#slack) page, `Slack` section needs to be updated to include the new `#cc-dev-searchportal` project channel.

## Description

- [x] `cc-dev-searchportal` exists in slack
- [x] Amend `/content/community/contents.lr` file to reflect new listing

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by satyampsoni** [comment]
This has been fixed pls close this issue
