### ISSUE TITLE
Pagination is not responsive in archive/old-tech-blog

### ISSUE THREAD

**Issue by Ruchitha2018** [creativecommons/creativecommons.github.io-source#69]
Pagination design is not responsive in archive/old-tech-blog.
![Pagination](https://user-images.githubusercontent.com/19637392/55606958-6dc84e00-5798-11e9-83bb-eb805a24b856.png)

Can I work on this issue?

**Comment by Ruchitha2018** [comment]
Can I make it responsive?

**Comment by kgodey** [comment]
Go ahead
