### ISSUE TITLE
[Bug] some minute grammatical issues

### ISSUE THREAD

**Issue by 0saurabh0** [creativecommons/creativecommons.github.io-source#700]
## Description

There are some punctuation and grammatical errors on :
https://opensource.creativecommons.org/programs/applicant-guide/#contributing
https://opensource.creativecommons.org/contributing-code/
## Reproduction

1. 
2. 
3. 
4. See error.

## Screenshots

Some of them are:
![Screenshot (60)](https://user-images.githubusercontent.com/97830220/221662903-4640ffdc-159d-4a7b-9a90-0da7ab51a0a6.jpg)
![Screenshot (61)](https://user-images.githubusercontent.com/97830220/221663093-f0af104c-89cf-416d-b1fd-b0b415cbcc74.jpg)

## Environment

 - Device: laptop
 - OS: (_eg._ iOS 13.5; Fedora 32)
 - Browser: Chrome
 - Version: (_eg._ 13; 73)
 - Other info: (_eg._ display resolution, ease-of-access settings)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by op-amateur** [comment]
Please assign me this issue. Thank you.

**Comment by 0saurabh0** [comment]
As mentioned above, a PR is already made for this.
