### ISSUE TITLE
Subscribe Button Issue: No Input Validation or Error Feedback

### ISSUE THREAD

**Issue by SoundaryaKoutharapu** [creativecommons/creativecommons.github.io-source#737]
## Description
When attempting to subscribe to the newsletter on the website without providing any input (such as an email address), the following behavior occurs:

Clicking on the "Subscribe" button refreshes the page.
There is no error message or feedback displayed.
The user is redirected to the homepage

## Reproduction
1. Navigate to the website's homepage.
2. Locate the "Subscribe" button for the newsletter.
3. Click on the "Subscribe" button without entering any input (e.g., email address).
4. Observe that the page refreshes and redirects to the homepage without providing any feedback or error message

## Expectation
Upon clicking the "Subscribe" button without entering any input, I expect to receive an error message or feedback indicating that input is required for the subscription process

## Screenshots

[bd11d637-5390-481a-b63a-76ac3facd735.webm](https://github.com/creativecommons/creativecommons.github.io-source/assets/71914071/1b6b51df-0ab4-4933-bd02-b801d0b8fe31)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by shivanshsin0203** [comment]
Hello everyone i have opened a PR is it correct can anyone check
