### ISSUE TITLE
[Bug] Broken Link in the ReadME section

### ISSUE THREAD

**Issue by ar-rana** [creativecommons/creativecommons.github.io-source#752]
## Description
The <a href="https://pipenv.pypa.io/en/latest/install/#installing-pipenv">Installing Pipenv</a> under the 'Installation - Prerequisites' section take to a 404 - page not found error

## Reproduction
1. Go to README.md 
2. Scroll to 'Installation' section
3. Under the section 'prerequisites' - 'GNU/Linux' 
4. Click on the 'Installing Pipenv' and see the problem

## Expectation
Should take to the Correct page

## Screenshots
Click: 
<img width="350" alt="Screenshot 2023-12-01 190648" src="https://github.com/creativecommons/creativecommons.github.io-source/assets/140689703/554573d0-8264-4ea4-a9da-42bffcf5c66c">
Redirected to this page: 

<img width="662" alt="Screenshot 2023-12-01 185619" src="https://github.com/creativecommons/creativecommons.github.io-source/assets/140689703/d6675e18-3607-4d8f-af93-7c361496d4a7">

## Environment
 - Device: laptop
 - OS: Windows
 - Browser: Chrome
 - Version: 119.0.6045.161 (Official Build) (64-bit) 

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by lemusalex797** [comment]
Buenos
