### ISSUE TITLE
Inconsistent height of div  

### ISSUE THREAD

**Issue by ShivamAhir** [creativecommons/creativecommons.github.io-source#762]
## Description
The height of the div container under "Featured Projects" is inconsistent. Currently, the height of the div is determined by its content, which can be improved for better UI consistency.

## Reproduction
Under the FEATURED PROJECTS there are inconsistent containers.

## Expectation
The div can have a fixed height, and we can enable scrolling for large content so that all divs appear similar in size.
## Screenshots
![image](https://github.com/creativecommons/creativecommons.github.io-source/assets/74092725/9ab2b3ea-64e9-4626-8d37-90f330baaa76)

## Environment

 - Device: (_eg._ iPhone Xs; laptop)
 - OS: (_eg._ iOS 13.5; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Version: (_eg._ 13; 73)
 - Other info: (_eg._ display resolution, ease-of-access settings)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by SamarthShukla17** [comment]
I would love to fix this issue. Could you asign this to me. Thanks

**Comment by ShivamAhir** [comment]
Hello @SamarthShukla17 , it's great to see your interest in contributing. However, I want to address this issue. The task you've expressed interest in isn't currently ready for work. Please refer to the Contribution Guidelines for more details.

**Comment by SamarthShukla17** [comment]
Thanks for the information. I really appreciate.
