### ISSUE TITLE
Add the ability for blog posts to be part of a series

### ISSUE THREAD

**Issue by kgodey** [creativecommons/creativecommons.github.io-source#89]
## Overview
It would be nice to show something like "This blog post is part of the <SERIES NAME> series" for blog posts that are related.

## Look and feel
Series can already be tracked via categories, but we would like a separate mechanism (like authors) to track them. **Please include design mock-ups or screenshots with any proposals or pull requests.**

## Series Examples
- https://creativecommons.github.io/blog/entries/cc-catalog-leverage-open-data-1/ is part of a three part series about the CC Catalog
- All posts that a given student posts during Google Summer of Code could be part of a series (to add more context to each individual post)

## Expected behavior
- Blog posts have a note associated with them that shows that the post is part of a series
- Each series has its own page that shows all the blog posts that are a part of that series
- In the backend, it should be implemented similar to how authors are implemented

**Comment by AndrejaP** [comment]
Hello. I'm an Outreachy applicant. I would like to work on this issue.

**Comment by kgodey** [comment]
Go ahead

**Comment by AndrejaP** [comment]
Thanks!

**Comment by AndrejaP** [comment]
Hello. It seems I bit off more than I could chew for now with this issue. I see it is not one of those that everyone can work on simultaneously so I feel bad occupying it while someone else might solve it faster and better. Maybe you can set it as available.

**Comment by kgodey** [comment]
@AndrejaP thanks for the update!

**Comment by techievivek** [comment]
@kgodey hello mam, i have created a PR for [custom 404 error page](https://github.com/creativecommons/creativecommons.github.io-source/issues/131), please verify it or suggest change if any.
I would like to work on this one now.
Thank you.

**Comment by kgodey** [comment]
@techievivek go ahead

**Comment by techievivek** [comment]
@kgodey mam, I was having my semester exams. After going through the above issue I realized we have a well-built functionality for categorizing blogs so there will no much need for another such idea of categorization but what we can do/ improve is as **you have suggested**, in front of every blog we can also show the category it falls in.
So the user can navigate to that category or open the blog to read.
I would like to showcase what I have done.
# Before
![before category](https://user-images.githubusercontent.com/35863227/70380089-ccfbe500-195b-11ea-88eb-b38df048c985.png)
 # After
- It has the badge color **theme color of CC**.
![categories in between](https://user-images.githubusercontent.com/35863227/70380094-e2710f00-195b-11ea-8abd-99d5ce4d1a83.png)
- It has badge color as **secondary** color of Bootstrap.
![badge-with-secondary](https://user-images.githubusercontent.com/35863227/70380101-0b919f80-195c-11ea-998f-ef4c9880a1c6.png)
- I have also experimented by keeping the categories on **top** for each blog.
![categories with top but without keyord](https://user-images.githubusercontent.com/35863227/70380129-6f1bcd00-195c-11ea-90ef-25d007149d48.png)

All the category badges are clickable. (Contains link to that category).
If you like this idea then we can proceed or else I will try doing excatly as you have suggested.
Thank you.

**Comment by kgodey** [comment]
hey @techievivek, I appreciate your initiative but this isn't what we're looking for. I don't think we need categories to be more visible on the blog entry list page.

A blog post series is not just another form of category, it's a specific way to denote multi-part blog posts. For example, all posts about a particular Google Summer of Code internship are part of a series. If you want to read the whole story of the project, you should be able to find the other posts in that series easily (while ignoring other GSoC projects and posts about that same project outside the GSoC period).

For example, see these examples of blog post series in WordPress: 
https://wpexplorer-themes.com/total/docs/post-series/
https://wordpress.org/plugins/wp-post-series/
https://wordpress.org/plugins/easy-post-series/
https://wordpress.org/plugins/organize-series/ (https://organizeseries.com/)

**Comment by techievivek** [comment]
@kgodey I was not able to differentiate, Thank you, mam, for helping out, I will start working in the direction you suggested and I have understood the requirement well now.

**Comment by techievivek** [comment]
@kgodey hello mam, i have created a PR with the detailed image explanation for every change, please have a look.
Thank you.

**Comment by techievivek** [comment]
@kgodey hello mam, i have created new PR with the change you guided me.
**1. For changing the position and removing whitespace before colon**
![series under post](https://user-images.githubusercontent.com/35863227/71122724-4242a200-2207-11ea-8054-7c023060d9b6.png)
<br>
**2. All post for a given series under the post content**
![list-all-post](https://user-images.githubusercontent.com/35863227/71122796-630af780-2207-11ea-98c6-405b37e539cb.png)
(There is one thing I can improve upon is I have hard-coded the URL for  **All series part** if you can guide me how lektor works with URL it will be a great help as the documentation is poor and I didn't get it).
**3. All series part**
![all-series](https://user-images.githubusercontent.com/35863227/71122954-ab2a1a00-2207-11ea-9c98-aaaa7effc51b.png)
**4. Admin Edit Area**
![edit-area](https://user-images.githubusercontent.com/35863227/71122969-b715dc00-2207-11ea-8e6d-82249307ca98.png)
